### PR TITLE
Enable SE100 in testkitgen and openjdk_regression tests

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
One successful build and disabled for now:

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk10_hs_openjdktest_x86-64_linux/

**Comment by sophia-guo** [comment]
Related with #228

**Comment by sophia-guo** [comment]
Good catch! Thanks, updated. Not knowing why I initially put this duplicate one.

**Comment by smlambert** [comment]
One additional place that should likely get updated is https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/Jenkinsfile_personal#L8 and L9, though its fine to put it in a separate PR if preferred.

**Comment by sophia-guo** [comment]
PR Build will also need to support it. I probably should try if it works for SCM with current Jenkins version. Otherwise maintain it separately is kind of pain.

**Pull request merged**
