### PR TITLE
Replace JAVA_BIN with TEST_JDK_HOME

### PR DESCRIPTION
**Pull request by renfeiw**
- remove JAVA_BIN export, replace it with TEST_JDK_HOME export

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
correlated PR: https://github.com/eclipse/openj9/pull/5601

**Comment by llxia** [comment]
Could you provide the grinder links? Thanks.

**Comment by renfeiw** [comment]
grinder for system test: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/328/

**Comment by renfeiw** [comment]
grinder for openjdk_regression test: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/337/

**Pull request merged**
