### PR TITLE
Change subset to version

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/179/

**Comment by llxia** [comment]
run aqa --sdk_resource=nightly --build_list=openjdk --target=sanity.openjdk.regular --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by llxia** [comment]
run aqa --sdk_resource=nightly --build_list=system --target=sanity.system.regular --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Review by smlambert — APPROVED** [review]
LGTM, thanks @renfeiw - directoriesChanged workflow failures are related to a known issue.  Nice to see the comment triggered workflow in action!

**Comment by karianna** [comment]
@renfeiw lots of failing checks, I assume that's deliberate because of your change?

**Comment by smlambert** [comment]
Failing checks are due to this issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/2291 (which I believe @xichen1 was going to look at and fix soon).  In the meantime there are manually run Grinder jobs that we as reviewers can refer to in order to verify that things are good.

**Comment by llxia** [comment]
The comment-triggered workflow works great. Love it. :)

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
