### PR TITLE
Add BumbleBench

### PR DESCRIPTION
**Pull request by piyush286**
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1379

- Add SIMD and string tests

Signed-off-by: Piyush Gupta <piyush286@gmail.com>

### CODE REVIEW

**Comment by piyush286** [comment]
Requesting review from @llxia and @smlambert. Thanks!

I've just added 4 tests to get started. I'll be adding more tests and enabling more platforms in future PRs. For now, I've marked all of them as `special` since it is easier to run all of them using `special.perf` for functionality check for this PR. I was wondering whether there is any way to run all the tests under one build file. I didn't want to use `sanity` or `extended` since that would also launch other perf tests marked with those levels. I can change the levels to whatever you suggest.

Sanity Job with `special.perf`. All tests are passing.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/718/console

```
16:01:44  TEST TARGETS SUMMARY
16:01:44  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
16:01:44  PASSED test targets:
16:01:44  	bumbleBench-SIMDDoubleMaxMinBench_0
16:01:44  	bumbleBench-ExactBench_0
16:01:44  	bumbleBench-StringConversionBench_0
16:01:44  	bumbleBench-StringHashBench_0
16:01:44  	bumbleBench-StringIndexOfBench_0
16:01:44  
16:01:44  TOTAL: 5   EXECUTED: 5   PASSED: 5   FAILED: 0   DISABLED: 0   SKIPPED: 0
```

**Comment by smlambert** [comment]
special is fine for now, we can reorganize at a later time should we want to.  

To run all tests in one build, since you can control what test targets are generated, what test material is built (and subsequently run) via BUILD_LIST, by merely setting BUILD_LIST=perf/bumblebench as you did in your Grinder, you run all of the tests... so in your case, because you set BUILD_LIST=perf/bumblebench, if you had tagged the tests as extended, and run TARGET=extended, it would have run all the extended tests within that directory.  In that same vein, 
if your BUILD_LIST=perf, and TARGET=extended, it would have picked up all the other tests tagged extended in the entire perf dir.

Grinder to show hotspot:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/726

Any specific reason to restrict these targets to jdk8?  (and to xlinux?)

**Comment by piyush286** [comment]
Thanks Shelley for the tip! I'll try the suggestion for the build list and target.

> Any specific reason to restrict these targets to jdk8? (and to xlinux?)

I was thinking of adding all tests for BumbleBench starting with x86 Linux and then finally enabling them on the other platforms/jdk versions. Anyway, let me just test and enable them right now.

**Comment by smlambert** [comment]
Eventually we should also update [perf doc for bumblebench](https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/perf#bumblebench) to a link that describes these microbenches.

**Pull request merged**
