### PR TITLE
Replaced JAVA_BIN in external/system-test of openjdk-tests repo

### PR DESCRIPTION
**Pull request by LongyuZhang**
- replaced JAVA_BIN and added TEST_JDK_HOME
[ci skip]

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
reviewers @llxia @soph

**Comment by llxia** [comment]
I noticed the possible inconsistent SDK in the external system test setup. Please open an issue for it. Thanks.

**Comment by LongyuZhang** [comment]
> We noticed the possible inconsistent SDK in the external system test setup. Please open an issue for it. Thanks.

The inconsistent SDK problem has been solved in the new commitment. Thanks.

**Comment by llxia** [comment]
Thanks @LongyuZhang for simplifying the logic.

In playlist.xml, we need to run groups (i.e., sanity, extended, etc), not specific targets because the specific target names may get changed. For example, `MauveMultiThreadLoadTest` is renamed to `MauveMultiThreadLoadTest_OpenJ9`.

https://github.com/AdoptOpenJDK/openjdk-tests/blob/c1b49a0a1f8cc15f6b3d698e8805c230dd56a442/systemtest/mauveLoadTest/playlist.xml#L118

**Pull request merged**
