### PR TITLE
Fix testKitGen output option

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw@ca.ibm.com <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @sophia-guo

**Comment by renfeiw** [comment]
make sanity

**Comment by sophia-guo** [comment]
add to whitelist

**Comment by sophia-guo** [comment]
ok to test

**Comment by sophia-guo** [comment]
PR triggered and passed. For unknown reason, no write permission to this  pull request. Will create an issue.
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/PR_sanity_openjdk_test_x86-64_linux/41/

Approve this PR.

**Pull request merged**
