### PR TITLE
Use env.HOME as a checkout reference

### PR DESCRIPTION
**Pull request by M-Davies**
Closes: #1803 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
Draft for now while awaiting review from @AdamBrousseau @sxa

**Comment by M-Davies** [comment]
Might be that the `openjdk_tests` file is executed before cygwin boots up and we don't have HOME manually set on the windows boxes? Someone would need to dig into one of them and take a look though

**Comment by M-Davies** [comment]
@AdamBrousseau At J9, do you have HOME set on windows itself (not cygwin)?

**Comment by M-Davies** [comment]
I setup a VM for myself using the [Adopt Playbooks](https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible#using-ansible-to-modify-vagrant-vm-remote-hosts-windows) and HOME is set to `/home/vagrant` in both powershell and cygwin so I don't think it's that.
Screenshot 2020-06-01 at 10 50 11

**Comment by sxa** [comment]
What about a normal windows command prompt?

**Comment by sxa** [comment]
Hmmm that's using a UNIX style path which suggests to me it was the cygwin setup that did it as a system / user environment variable

**Comment by M-Davies** [comment]
@sxa Same variables. UNIX style path for HOME is also seen on command prompt

**Comment by sxa** [comment]
OK it must have been set as an environment variable by the cygwin installer then, but for some reason not on the affected machines. Do we know how many machines are affected? Presumably not all of them...

**Comment by M-Davies** [comment]
A quick look through the Failed jobs I've seen it on at least these four machines. But there could be more
```
test-aws-win2019-x64-1
test-aws-win2019-x64-2
test-softlayer-win2012r2-x64-2
test-azure-win2012r2-x64-1
```

**Comment by M-Davies** [comment]
The only online [test Windows machine](https://ci.adoptopenjdk.net/label/test/) that I didn't see producing this error is https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-1

**Comment by AdamBrousseau** [comment]
Looking at an OpenJ9 machine. I don't see HOME set in the Windows config nor in a command prompt.

Are all the Adopt (win) machines connected via JNLP (Windows Service)? All ours are ssh direct from master.

**Comment by sxa** [comment]
We do not have ssh on our windows machines - they all call back to the jenkins server

**Comment by Willsparker** [comment]
@M-Davies You've put `test-azure-win2012r2-x64-1` in the list, and then said you don't see the error on it? Those are the only 4 online windows machines

**Comment by M-Davies** [comment]
My mistake, that machine also sees this error https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/227/console

**Comment by Willsparker** [comment]
From the looks of it, we do have `HOME` set on :
```
test-aws-win2019-x64-1
test-softlayer-win2012r2-x64-2
test-azure-win2012r2-x64-1
```
At least in the same way you checked it (`printenv` on both cygwin64 terminal & `cmd`). 
(I don't have the credentials for the second `aws` machine).

**Comment by Willsparker** [comment]
I get the impression it could be due to differences in the Jenkins specific plugins (`scm` for instance), assuming the OpenJ9 machines are setup with our playbooks with minimal change, and OpenJ9 use a different CI to Adopt. I'm unable to find any instance on any of those machines where `HOMEPATH` is defined, but `HOME` isn't.
Given that the `$HOME` variable is _there_  and AFAIK there isn't any other issues about the `$HOME` variable not being found, I don't think it's an issue to just use `HOMEPATH` :-)

**Comment by AdamBrousseau** [comment]
Has this PR actually been tested at Adopt? Since home is in the env, maybe it's something plugin/Jenkins side as Will says.

**Comment by M-Davies** [comment]
Hmm. It looks like this PR doesn't work with HOMEPATH either (I really need to remember that grinders can test openjdk-test branches!)
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3132/console

**Comment by AdamBrousseau** [comment]
Do we recall the reason the Adopt Win machines are setup using jnlp and not ssh? At this point that's the only difference i see.

**Comment by M-Davies** [comment]
It seems `HOMEPATH` needs to be prepended with `env` to pick it up
https://github.com/AdoptOpenJDK/openjdk-tests/compare/master...M-Davies:repo_scm_test
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3135/console

**Comment by M-Davies** [comment]
Doing the same for `HOME` works too on windows.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3136/console

I'll do some more testing with other OS's to ensure it doesn't affect them. If that works out, it should be ok to shift this PR to instead use `env.HOME` over all of the other ideas discussed here.

**Comment by M-Davies** [comment]
I've done some testing with internal and Adopt jenkins instances. Both work with `env.HOME` on all the platforms I could test. I'll update this PR then await some more reviews

**Comment by karianna** [comment]
Hmm, I wasn't able to bounce jenkins over the weekend. I wonder if there's a plugin concern here.

**Comment by M-Davies** [comment]
Kicked off
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/614/
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9-windowsXL/355/
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-hotspot/550/
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/607/

to see if the bounce last night did anything.

**Comment by M-Davies** [comment]
Looks like the bounce didn't fix anything https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/231/console is still showing the issue. Can this be pushed through if everyone is happy with it?

**Comment by sxa** [comment]
The adoptopenjdk restart was done yetserday but a further one occurred this afternoon

**Comment by M-Davies** [comment]
Trying again with https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/979/console after the 2nd restart

**Comment by M-Davies** [comment]
Same error after the 2nd restart https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/226/console

**Comment by karianna** [comment]
> Same error after the 2nd restart https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/226/console

I got a bit lost with the very long thread here. Is the https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/226/console test effectively manually applying this PR and it's not working?

**Comment by M-Davies** [comment]
> > Same error after the 2nd restart https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/226/console
> 
> I got a bit lost with the very long thread here. Is the https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/226/console test effectively manually applying this PR and it's not working?

It was thought that the jenkins restarts would have resolved the error raised in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1803 so merging of this was put on hold. However, this has turned out not to be the case and as such, this PR is still a valid fix for the original error. 

This has been manually applied in [testing grinders](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1804#issuecomment-636918759) and it seems to work (both on adopt and ibm grinders) so I'm just waiting on @smlambert 's review to make sure she is happy with the changes here.

**Comment by M-Davies** [comment]
Running https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/981/console to confirm the fix worked

**Pull request merged**
