### PR TITLE
Add libpath

### PR DESCRIPTION
**Pull request by psoujany**
Adding LIBPATH  to jtreg commands, so that test doesn't fail due to missing libraries.

This will resolve openj9-openjdk-jdk11-zos/issues/397.

Signed-off-by: Pasam Soujanya psoujany@in.ibm.com

### CODE REVIEW

**Review by karianna — APPROVED** [review]
lgtm

**Review by smlambert — COMMENTED** [review]
Grinders on various platforms should be kicked off (particularly windows)

**Comment by llxia** [comment]
I am not able to reproduce the original issue `CEE3501S The module X11_64.dll was not found` on zos (Grinder/13772)
Noticed that your Grinder ran on a specific machine `fyrec520.vmec.svl.ibm.com`. If this is an issue on a specific machine, this PR should not be checked in. We need to check on the machine configuration.

**Review by smlambert — CHANGES_REQUESTED** [review]
Agreed, fixing the machine config issue is the right approach.  Modifying the test layer to compensate for machine issues leads to problems and unexplainable tech debt down the road.

Will leave this open but block it from accidentally being merged until confirmation its machine specific.

**Comment by psoujany** [comment]
> 
> 
> Agreed, fixing the machine config issue is the right approach. Modifying the test layer to compensate for machine issues leads to problems and unexplainable tech debt down the road.
> 
> Will leave this open but block it from accidentally being merged until confirmation its machine specific.

I tried parallel runs on most of the z/OS nodes, I see LIBPATH is set on jenkins nodes through TKG scripts. 

LIBPATH=/usr/lpp/rsusr/rocket/lib:/usr/lpp/rsusr/rocket/lib/perl5/5.24.0/os390/CORE:/usr/lib:.:/usr/lpp/rsusr/rocket/lib:/usr/lpp/rsusr/rocket/lib/perl5/5.24.0/os390/CORE:/usr/lib:.:/usr/lpp/java/java180/J8.0_64/lib/s390x/compressedrefs:/usr/lpp/java/java180/J8.0_64/lib/s390x/j9vm:/usr/lpp/java/java180/J8.0_64/lib/s390x:/usr/lpp/java/java180/J8.0_64/../lib/s390x:/usr/lpp/java/java180/J8.0_64/lib/icc:/usr/lpp/java/java180/J8.0_64/lib/s390x::/usr/lpp/java/java180/J8.0_64/lib/s390x/compressedrefs:/usr/lpp/java/java180/J8.0_64/lib/s390x

I don't see X11.dll issue anymore in the tests. I think this change is no more valid. Please suggest. Thank you.
**Grinder:**
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/13777/

**Comment by llxia** [comment]
@psoujany Thanks for verifying. It is great that this issue does not exist anymore. I will close this PR.

Just to clarify, TKG appends LIBPATH with JDK related path for testing purpose. It does not set machines specific path, such as `/usr/lib`. 

And for future reference, the original issue (openj9-openjdk-jdk11-zos/issues/397) was based on a Grinder that ran 5 months ago. Since we are constantly updating test material/framework/pipeline/machines and adding new features, it would be good to validate if the issue is reproducible first. Thanks.

**Pull request closed without merging**
