### PR TITLE
Add step to display junit report for elasticsearch onto jenkins gui

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Add step to display junit report for elasticsearch onto jenkins gui
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
I don't see Test Results on the Grinder, I am guessing the copy did not work as expected?

**Comment by Mesbah-Alam** [comment]
What was confusing me is that that `rm -rf` command was not deleting the workspace, but simply deleting the( elasticsearch) test specific folder  `rm -f -r "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15386746979099/elasticsearch_test`. 

The step to delete the workspace should have deleted `/home/jenkins/workspace/Grinder/`

**Comment by smlambert** [comment]
If its only elasticsearch dir getting deleted, perhaps there is some [automatic clean up happening by gradle](http://mrhaki.blogspot.com/2010/10/gradle-goodness-automatic-clean-tasks.html) for Elasticsearch.  Not sure, perhaps you can check through their gradle config files to confirm.

**Comment by Mesbah-Alam** [comment]
I did a different experiment: I ran an existing app test (jenkins test) using Grinder, and for that too, the junit reports were not displayed! 
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/249/

Jenkins test is part of the build already and we know for a fact that it does perform the reports processing properly, as jenkins test results are [reported ](https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_x86-64_linux/189/testReport/) in the build. 

Hence, I am suspecting that something in the new Grinder build itself is throwing us off here.

**Comment by smlambert** [comment]
ok, likely a switch over issue, in a separate PR we can and should change grinder to also run the post() method to share results.

**Comment by Mesbah-Alam** [comment]
Thanks for the approval. I am quite sure we will see the junit reports for elasticsearh in the main build. 

I created a new issue for the Grinder problem : https://github.com/AdoptOpenJDK/openjdk-tests/issues/620

**Pull request merged**
