### PR TITLE
Change Mode140 to Mode145 in special.system tests

### PR DESCRIPTION
**Pull request by llxia**
Related: https://github.com/eclipse/openj9/issues/11105

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Internal Grinder/12259

**Comment by llxia** [comment]
FYI @Mesbah-Alam @pshipton

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by pshipton** [comment]
lgtm. Hopefully this mode is added now, I don't think it existed before.

The reason we are doing this is because gencon is the default for many years and not optthruput. If we're only going to test one mode with -Xshareclasses it might as well be the default gc policy.

**Pull request merged**
