### PR TITLE
Enable CS test cases on Power

### PR DESCRIPTION
**Pull request by MrTrader8**
There are some CS test cases that were not enabled on Power.
This commit enables all CS testing on the Power platform.

Signed-off-by: Andrew Gao <andrewgao98@gmail.com>

### CODE REVIEW

**Comment by MrTrader8** [comment]
I have the links to the grinders for the tests that were enabled if needed

**Comment by Mesbah-Alam** [comment]
This PR is related to : https://github.com/AdoptOpenJDK/openjdk-tests/pull/1302/files

**Comment by Mesbah-Alam** [comment]
@MrTrader8 : Yes, it'd be good to post the Grinder links here for reference. If they are internal grinder links, you could post partial links (e.g. https://github.com/AdoptOpenJDK/openjdk-tests/pull/1302#issuecomment-527489220)

**Comment by MrTrader8** [comment]
Internal Grinders(AIX):
/view/Test_grinder/job/Grinder_Advanced/968/
/view/Test_grinder/job/Grinder_Advanced/969/
/view/Test_grinder/job/Grinder_Advanced/970/
/view/Test_grinder/job/Grinder_Advanced/971/
/view/Test_grinder/job/Grinder_Advanced/972/
/view/Test_grinder/job/Grinder_Advanced/974/
/view/Test_grinder/job/Grinder_Advanced/981/

**Comment by Mesbah-Alam** [comment]
@MrTrader8 : Please note, you can run Grinders at Adopt with AIX right now too. The compile issue has been fixed: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1972/console

**Pull request merged**
