### PR TITLE
Move problem lists

### LINKED ISSUE #2400: Collapse all openjdk problem list files into an excludes folder
**👾 Description of the issue**

This is 'tidy-ness' item.  We currently have all problem lists for all versions and vmImpls directly in the [openjdk](https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/openjdk) directory of this repo.  It makes that directory quite cluttered and will only get worse.  

This enhancement issue proposes to move all the problem list files into a new folder openjdk/excludes.  If we do move them there, we will need to update the PROBLEM_LIST_FILE variable in openjdk.mk to the new location.  See various ways it can be set, starting at [openjdk.mk/L137](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/openjdk.mk#L137).

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing pieces or a problem they will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

### PR DESCRIPTION
**Pull request by patkarns**
Fixes #2400

### CODE REVIEW

**Review by sophia-guo — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Grinder for jdk_lang/hs/jdk11/x86_linux: 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/225

seems to have some trouble:

```
15:35:28  -w ""/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../TKG/output_16172193276035/jdk_lang_1"/work" \
15:35:28  -r "/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../../jvmtest/openjdk/report" \
15:35:28  -jdk:"/home/jenkins/workspace/Grinder_TKG/openjdkbinary/j2sdk-image" \
15:35:28  -exclude:"/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../openjdk/openjdk-jdk/test/jdk/ProblemList.txt" \
15:35:28  -exclude:"/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../../jvmtest/openjdk/excludes/ProblemList_openjdk11.txt" \
15:35:28  "/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../openjdk/openjdk-jdk/test/jdk:jdk_lang"; \
15:35:28  if [ $? -eq 0 ] ; then echo ""; echo "jdk_lang_1""_PASSED"; echo ""; cd /home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../TKG/output_16172193276035/jdk_lang_1"; else echo ""; echo "jdk_lang_1""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../TKG/output_16172193276035/TestTargetResult";
15:35:28  Directory "/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../TKG/output_16172193276035/jdk_lang_1/work" not found: creating
15:35:28  Directory "/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../../jvmtest/openjdk/report" not found: creating
15:35:28  Error: Bad parameters specified: One of the files you specified was not found. The error reported was:
15:35:28  /home/jenkins/workspace/Grinder_TKG/jvmtest/openjdk/excludes/ProblemList_openjdk11.txt (No such file or directory)
15:35:28  
15:35:28  jdk_lang_1_FAILED
```

**Review by smlambert — CHANGES_REQUESTED** [review]
Think it may be a case of us not copying the excludes folder over into the DEST folder where the tests are run...  see https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L272

**Comment by sophia-guo** [comment]
Correct @smlambert ! I forgot that.

**Comment by sophia-guo** [comment]
Looks good now : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/226/console

**Review by smlambert — APPROVED** [review]
thanks @patkarns !

**Pull request merged**
