### PR TITLE
Change Renaissance 0.9.0 to 0.11.0 in build.xml

### PR DESCRIPTION
**Pull request by xfxcwynlc**
Change the download address to v0.11.0 at line 37.
Closes: #2298

### CODE REVIEW

**Review by sophia-guo — APPROVED** [review]

**Comment by sophia-guo** [comment]
LGTM. Just wondered what's the difference between GPL version and MIT version? Looks like former releases have two versions and we downloaded MIT version. Now the latest release only have the GPL version. Is it good using GPL version? @smlambert

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2314#issuecomment-787911322 - GPL is fine in this case, we are neither changing or distributing it, but merely running this benchmark (and given MIT licensed one is no longer offered we will proceed with this one).

**Comment by smlambert** [comment]
Grinder (jdk8/j9/sanity.perf): https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Perf/18
Grinder (jdk16/hs/sanity.perf): https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Perf/19

**Review by smlambert — APPROVED** [review]
Running Grinders to see if this update fixes some issues with jdk16 runs (so that the related issues may also be closed, but either way, we want this update, so will merge).

**Pull request merged**
