### PR TITLE
Update spec name for arm64_mac

### PR DESCRIPTION
**Pull request by renfeiw**
- format spec name to match auto detection

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
related comment: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2501#issuecomment-819594721

**Comment by renfeiw** [comment]
Once this is merged, we also need to update property file in TKG: https://github.com/adoptium/TKG/blob/master/resources/buildPlatformMap.properties

**Review by smlambert — APPROVED** [review]
Thanks @renfeiw - I will update the LABELs on the machine to match (once merged).

**Review by sophia-guo — APPROVED** [review]
LGTM

**Comment by sophia-guo** [comment]
Approved. Leave to @ShelleyLambert to merge as machine label need to be updated.

**Comment by smlambert** [comment]
Machine labels updated.

Going to assume based on https://github.com/AdoptOpenJDK/openjdk-tests/pull/2510#issuecomment-819615792
that a PR for https://github.com/adoptium/TKG/blob/master/resources/buildPlatformMap.properties can follow this merge (not required beforehand).

**Comment by renfeiw** [comment]
Thanks. The properties file change is here: https://github.com/adoptium/TKG/pull/182

**Pull request merged**
