### PR TITLE
Add Artifactory link to build description

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Test Build
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/220/

**Comment by llxia** [comment]
Could you provide a Grinder link? Thanks

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/641/

**Comment by llxia** [comment]
What is the difference between this `Artifacts` link and the default artifactory link?
Screen Shot 2019-03-25 at 9 12 33 PM

**Comment by AdamBrousseau** [comment]
The default (green line and circle) is a link to the webui for the Build artifact. On the OSS version, you can't easily navigate from there to the artifacts. The new one links to the file browser level directly to the folder where the artifacts are stored. In this case nothing was uploaded because the build was green so you get a 404. We should probably wrap the upload in a condition and check if there is anything to upload first. 

Related eclipse/openj9#5212. Note that in the OpenJ9 change we have the full URLs linked for a direct download. Where as here we just link to the folder because we don't know what artifacts, if any, exist.

**Comment by llxia** [comment]
ah, I see. This is for Artifactory OSS version.

**Pull request merged**
