### PR TITLE
Support for jitaas testing

### PR DESCRIPTION
**Pull request by renfeiw**
- Invoke teardown before and after to ensure jitaas is killed

related PR: https://github.com/eclipse/openj9/pull/3059

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Is this WIP? Confused that maketest_jitaas.sh is exactly same as maketest.sh?

**Comment by renfeiw** [comment]
Yes, maketest_jitass.sh is same as maketest.sh for now. It's a template for the JIT team to add pretest and posttest targets. Once this is in, please feel free to add them. @harryyu1994
IMO the server watchdog should be added in the maketest_jitass.sh, as the Jenkins file does not have visibility of what subprocesses are running in the makefile.

**Comment by AdamBrousseau** [comment]
While I agree that this approach makes sense from a test harness perspective, from an infrastructure perspective, my concern is that if the makefile has started the server, and then has a hard failure during the tests, the cleanup command will not get executed and the server will continue to run.

**Comment by smlambert** [comment]
Is there a way of thinking about this, naming this more generically?  jitaas may not be the only feature in the future to need additional things set up in advance of the test execution.  Most modern test harnesses have a setup/execute/teardown piece.  Calling the script make_jitaas may be confusing if we have other features later that also require some sort of pre-test setup.

**Comment by llxia** [comment]
This cannot be merged before https://github.com/eclipse/openj9/pull/3059

**Pull request merged**
