### PR TITLE
Add support for Elasticsearch Testing in Docker Generation

### PR DESCRIPTION
**Pull request by james-crowley**
This PR will enable support for using elasticsearch as an external test with Docker generation. Currently elasticsearch is the only test not enabled in the external test directory.

### CODE REVIEW

**Comment by james-crowley** [comment]
Hitting a couple issues, first the required version of Java for the new release of elasticsearch is Java 13. You can find more information about this issue in #1720.

Second, a couple grinders are failing. The main grinder that fails is [2770](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2770/console). It seems to build the elasticsearch binary fine but when it goes to run the test suite it fails. I suspect that it is building a `x86` binary when the system is `s390x`, thus causing it to fail.

**Comment by james-crowley** [comment]
Running some sanity checks to see any errors we are having with Adopt via hotspot and openj9.

**Hotspot Test _without_ Exclude Tests**

- Grinder [2775](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2775/console) - Failed when running tests.


**Hotspot Test _with_ Exclude Tests**

- N/A

**OpenJ9 _without_ Exclude Tests**

- 

**OpenJ9 _with_ Exclude Tests**

- Grinder [2777](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2777/console) - Failed when trying to pass in exclude tasks

**Comment by james-crowley** [comment]
@ShelleyLambert and @llxia All that should be left in this PR is finding out what else to exclude from run. It seems that is where I left off last time. Running some grinders now to find out which test fail.

**Comment by llxia** [comment]
Could you please add `source $(dirname "$0")/test_base_functions.sh` and `echo_setup` in `elasticsearch-test.sh`. Simliar to PR #1875. We need information so that we can display it in TRSS. Thanks.

FYI @renfeiw

**Comment by james-crowley** [comment]
@llxia I added in the needed changes you requested. Let me know if the changes look okay. Hopefully, we can merged this PR sometime this week!

**Comment by smlambert** [comment]
I plan to merge this today or tomorrow and deal with any 'fallout' after its in, so that we can progress it.  

Please let me know if you have any concerns with this approach @llxia @james-crowley

**Review by smlambert — APPROVED** [review]

**Review by llxia — APPROVED** [review]
Thanks @james-crowley

**Pull request merged**
