### PR TITLE
Fix 11.0.9 CLDR_11 and Chinese and Taiwanese data

### LINKED ISSUE #1953: MBCS_Tests_CLDR_11 testcases were failed by 11.0.9+5 EA
**Describe the bug**
According to following link "MBCS_Tests_CLDR_11_*" testcases were failed.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/130/tapResults/
1 files	371 tests, 79 ok, 4 not ok, 288 skipped, 0 ToDo, 0 Bail Out!
Following testcases were failed
 120 - - MBCS_Tests_CLDR_11_ja_JP_linux_0
 121 - - MBCS_Tests_CLDR_11_ko_KR_linux_0
 122 - - MBCS_Tests_CLDR_11_zh_CN_linux_0
 123 - - MBCS_Tests_CLDR_11_zh_TW_linux_0

Java version information:
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+5-202009102351)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-29b417fac, JRE 11 Linux amd64-64-Bit Compressed References 20200910_756 (JIT enabled, AOT enabled)
OpenJ9   - 29b417fac
OMR      - 58b0c1838
JCL      - 5c901dad28 based on jdk-11.0.9+5)

**To Reproduce**
Grinder_Simple parameters link is as follows:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/130/parameters/
PLATFORM: x86-64_linux
BUILD_LIST: functional/MBCS_Tests
TARGET: special.functional
SDK_RESOURCE: nightly
JDK_VERSION: 11
JDK_IMPL: openj9

**Expected behavior**
MBCS_Tests_CLDR_11 should not be failed.
It seems this issue is related by JDK-8248824
JDK-8248824 SimpleDateFormat :: format - Zone Names are not reflected correctly during run time
https://bugs.openjdk.java.net/browse/JDK-8248824

### PR DESCRIPTION
**Pull request by takiguc**
Fixes #1953
Signed-off-by: Ichiroh Takiguchi takiguc@jp.ibm.com

### CODE REVIEW

**Comment by takiguc** [comment]
I applied following changes:

- Change CLDR_11 data files for 11.0.9
- Remove unused files
- Fix setup shell and data files for regex testcase
- Fix setup shell and data files for StAX testcase
- Fix garbled data for i18n testcase
- Add data for codepage testcase
- Add GB18030 related file for nio testcase

**Comment by takiguc** [comment]
**Test result**

Linux x64 11.0.9
1 files  371 tests, 83 ok, 0 not ok, 288 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/131/tapResults/

Windows x64 11.0.9
1 files  371 tests, 82 ok, 0 not ok, 289 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/132/tapResults/

AIX 11.0.9
1 files  371 tests, 216 ok, 0 not ok, 155 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/133/tapResults/

**Comment by takiguc** [comment]
**Test result**

AIX jdk8u272-b07
1 files  174 tests, 69 ok, 0 not ok, 105 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/134/tapResults/

Windows x64 jdk8u272-b07
1 files  174 tests, 54 ok, 0 not ok, 120 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/135/tapResults/

Linux x64 jdk8u272-b07
1 files  174 tests, 53 ok, 0 not ok, 121 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/136/tapResults/

AIX jdk8u265-b01
1 files  174 tests, 69 ok, 0 not ok, 105 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/137/tapResults/

Windows x64 jdk8u265-b01
1 files  174 tests, 54 ok, 0 not ok, 120 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/138/tapResults/

Linux x64 jdk8u265-b01
1 files  174 tests, 53 ok, 0 not ok, 121 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/139/tapResults/

AIX jdk-11.0.8+10
1 files  371 tests, 216 ok, 0 not ok, 155 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/140/tapResults/

Windows x64 11.0.8+10
1 files  371 tests, 82 ok, 0 not ok, 289 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/141/tapResults/

Linux x64 jdk-11.0.8+10
1 files  371 tests, 83 ok, 0 not ok, 288 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/142/tapResults/

**Review by smlambert — APPROVED** [review]
thanks @takiguc !

**Pull request merged**
