### PR TITLE
Add Jenkins files for Linux s390

### PR DESCRIPTION
**Pull request by vsebe**
Add Jenkins files for 31 bits and Large Heap platforms.

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@llxia please review, thank you!
Please see internal pipelines.

**Comment by llxia** [comment]
Could we follow a similar naming conversion and have`openjdk_s390x-64_linux_xl` and `openjdk_s390x-31_linux`?

**Comment by vsebe** [comment]
s390x usually designates a 64bits architecture and s390 a 31 bits architecture but generally s390 refers to Linux on Z. Thus s390-31, s390-64 would probably be better. 
In order to be consistent, the existing script - [openjdk_s390x_linux](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_s390x_linux) - would also have to follow the naming converntion. @llxia - What's the impact on changing it?

**Comment by llxia** [comment]
Talked with @vsebe , I agree that `openjdk_s390x_linux` also needs to follow the naming convention. But changing the existing script means we need to regenerate the test jobs and change upstream scripts. We will keep the name as it is for now.

**Pull request merged**
