### PR TITLE
Run chmod on .sh files under devtools directory only

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves backlog/issues/430

Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test with jck-8 extended.jck set (which contains all devtools tests) on Linux : Grinder/12851 
(Note: the original reason for adding the chmod step was related to a failure under devtools).

**Comment by Mesbah-Alam** [comment]
All devtools related tests pass when run with this PR. Details here: in internal Grinder/12851

**Comment by Mesbah-Alam** [comment]
Test on z/OS with JDK 11 where no devtools folders exist so no chmod should occur: 

Internal Grinder/12869

**Comment by llxia** [comment]
Git does track the executable bit, so we would prefer to store the executable bit directly in the repo.

**Comment by Mesbah-Alam** [comment]
Hi @llxia , 

Following your comment, I updated the execution bits in the devtool scripts in the JCK 8 repo in my [branch](https://github.ibm.com/runtimes/JCK8-unzipped/pull/22) (basically did chmod 777 on all the related *.sh files under devtools) and ran the devtools tests, but there are failures in the test for which the [original issue](https://github.ibm.com/runtimes/backlog/issues/188) raised : `jck-devtools-java2schema-CustomizedMapping_0`: 

Please see this internal Grinder: 12879. 

So, it appears that updating the execution bit in the files in the git repo doesn't work. 

The failures of course go away if chmod command is run explicitly after download of the JCK materials, as evident in the previous build I had run with the chmod command still in the PR: 

Please see this internal Grinder Grinder/12851 (result for jck-devtools-java2schema-CustomizedMapping test). 

So, as I had stated in https://github.ibm.com/runtimes/backlog/issues/430#issuecomment-26531115 , we can have the chmod command in the script since with this PR we will only be chmod'ing a specific set of .sh files in JCK repo - meaning time will not be a concern.

**Comment by Mesbah-Alam** [comment]
@llxia - I've updated this PR and simply omitted the chmod step from this script. Please see testing results reported in backlog/issues/430. 

Please note, this PR should be delivered together with the PR in the test repo where permission bits have been set.

**Review by llxia — APPROVED** [review]
LGTM 
Thanks @Mesbah-Alam

**Pull request merged**
