### PR TITLE
Adding Jacoco tests to external group

### PR DESCRIPTION
**Pull request by nikolamilijevic1**
Commit adds jacoco test suite to the openj9 external group

Signed-off-by: <nmilijev@uwaterloo.ca> Nikola Milijevic

### CODE REVIEW

**Comment by nikolamilijevic1** [comment]
@llxia @renfeiw 
| BUILD | PLATFORM | TARGET  | BUILD_LIST | JAVA_VERSION |
|--- | --- | --- | --- |--- |
| Grinder/4941| x86-64_linux| MachineInfo,jacoco_test| external/jacoco| 8 |
| Grinder/4942| ppc64le_linux| MachineInfo,jacoco_test| external/jacoco| 8 |
| Grinder/4943| s390x_linux| MachineInfo,jacoco_test| external/jacoco| 8 |

https://ci.adoptopenjdk.net/view/Test_grinder/

**Review by llxia — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by sophia-guo** [comment]
Dockerfile is dynamically generated under currently framework. Shouldn't we stop delivering Dockerfile? Or it's for documentary reason?

**Pull request merged**
