### PR TITLE
Only generate child jobs if they do not exist

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
- https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8083/ // parallel on 2 machines. Both child jobs exist, so no child job needs to be generated
- https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8087/ //parallel on 3 machines. One child job is missing, so the missing child job (Grinder_testList_2) is generated
```
00:01:54.567  Grinder_testList_0 jobIsRunnable: true
[Pipeline] library
00:01:54.735  Only using first definition of library openjdk-jenkins-helper
[Pipeline] echo
00:01:55.760  Grinder_testList_1 jobIsRunnable: true
[Pipeline] library
00:01:55.919  Only using first definition of library openjdk-jenkins-helper
[Pipeline] echo
00:01:57.106  Grinder_testList_2 jobIsRunnable: false
[Pipeline] parallel
[Pipeline] { (Branch: testList_2)
[Pipeline] echo
00:01:57.324  Test job Grinder_testList_2 doesn't exist, set test job Grinder_testList_2 params
[Pipeline] jobDsl
00:01:57.475  Processing DSL script openjdk-tests/buildenv/jenkins/testJobTemplate
00:02:41.286  LEVELS: [sanity]
00:02:41.286  JDK_VERSIONS: [8]
00:02:41.286  GROUPS: [functional]
00:02:41.286  ARCH_OS_LIST: [x86-64_linux]
00:02:47.370  Added items:
00:02:47.370      GeneratedJob{name='Grinder_testList_2'}

```

**Comment by llxia** [comment]
FYI @AdamBrousseau

**Comment by AdamBrousseau** [comment]
For the record, I think you pointed out that if we needed to regenerate children we could use the regular autogen job.

**Comment by llxia** [comment]
Yes, that is correct. Also, for jenkins that does not have `openjdk-jenkins-helper@master` configured (i.e., openj9 Jenkins), the script will always generate new child jobs. https://ci.eclipse.org/openj9/job/Grinder/1639/console

**Review by smlambert — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Review by renfeiw — APPROVED** [review]
LGTM

**Pull request merged**
