### PR TITLE
Shorten modularity test names to suit Windows MAX_PATH limit

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Related to eclipse/openj9#11365

Signed-off-by: Mesbah_Alam@ca.ibm.com Mesbah_Alam@ca.ibm.com

@llxia @pshipton

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Test : Internal/Grinder/12462

**Comment by Mesbah-Alam** [comment]
Related https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/383

**Comment by Mesbah-Alam** [comment]
I've shortened the names of modularity tests in the playlist in this PR. This is to be delivered along with its related system test PR : https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/383 - where class names and some of the enums used were also shortened. 

These two PRs will hopefully resolve https://github.com/eclipse/openj9/issues/11365 . 

(Note:The paths formed in these tests when run from Grinder are shorter than those in live builds, as live builds themselves has longer name strings than "Grinder". Hence, we should deliver these PRs and watch the live builds to confirm the fix).

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
