### PR TITLE
Set common env variables globally

### PR DESCRIPTION
**Pull request by sophia-guo**
Set common env variables globally in Jenkinsfile_personal

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
actually, before you commit this @sophia-guo, is it possible for you to add a label to the choices called sw.tool.docker ?  as we have been using linux machines for it, but now I am not certain that all linux machines have it (possibly just 4 of 6).  

And once its installed on other platforms, selecting docker will give a bigger set of machines to send jobs to

**Comment by sophia-guo** [comment]
@smlambert updated with label sw.tool.docker and compressedref spec.

**Comment by smlambert** [comment]
haha, ok.  You and @Mesbah-Alam are moving fast!  It is great... now that I see how many different choices there are, I wonder that we might just switch this param to be a string (with all the current choices showing up below the text field in the Jenkins UI, so we avoid having to continue to change this file for this field).  see note on #298

**Comment by sophia-guo** [comment]
Agreed. Actually this field was a choice, then changed to a string, then changed back to a choice :) Will change back to a string.

**Comment by smlambert** [comment]
Yes, apologies for the churn on this one...  :)  and thanks for taking it on.

**Pull request merged**
