### PR TITLE
Enable jre tests for jdk11

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/448/

**Comment by karianna** [comment]
@llxia Latest run for 11.0.1+b13 Hotspot got this:

```
===============================================
Running test jdk_math_jre_0 ...
===============================================

jdk_math_jre_0 Start Time: Sat Nov 24 20:39:44 2018 Epoch Time (ms): 1543091984934

variation: NoOptions

JVM_OPTIONS:  

{ mkdir -p "/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15430909402529/jdk_math_jre_0"; \

cd "/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15430909402529/jdk_math_jre_0"; \

"/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xmx512m -jar "/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/jtreg/lib/jtreg.jar" \

-agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error -ignore:quiet -timeoutFactor:4 -xml:verify -concurrency:4  -vmoptions:"-Xmx512m  " \

-w "/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/work" \

-r "/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/report" \

-compilejdk:"/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdkbinary/j2sdk-image/bin/.." \

-jdk:"/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdkbinary/j2jre-image" \

-exclude:"/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../openjdk_regression/openjdk-jdk/test/jdk/ProblemList.txt" \

-exclude:"/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/ProblemList_openjdk11.txt" \

"/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../openjdk_regression/openjdk-jdk/test/jdk:jdk_math"; \

if [ $? -eq 0 ] ; then echo ""; echo "jdk_math_jre_0""_PASSED"; echo ""; cd /home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "jdk_math_jre_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15430909402529/TestTargetResult";

Error: JDK not found: /home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdkbinary/j2jre-image

jdk_math_jre_0_FAILED
jdk_math_jre_0 Finish Time: Sat Nov 24 20:39:45 2018 Epoch Time (ms): 1543091985593
```

**Comment by llxia** [comment]
@karianna is this the test build that you are referring to? https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_linux/83/consoleFull

If so, the upstream build only has 'jdk'. It does not contain `jre`: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/26/

**Comment by sophia-guo** [comment]
@karianna this jdk_jre test need jdk to comiple test. That is if there is no jdk, test will fail. When will  jdk11u builds have jre image available? I mixed up jdk11 and jdk11u. And enabled the test as JDK11 builds have jre image. If it takes time I will re-disable it.

**Comment by karianna** [comment]
> @karianna is this the test build that you are referring to? https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_linux/83/consoleFull
> 
> If so, the upstream build only has 'jdk'. It does not contain `jre`: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/26/

It was actually https://ci.adoptopenjdk.net/job/openjdk11_hs_openjdktest_x86-64_linux/82/console but it's the same error.

**Comment by karianna** [comment]
> @karianna this jdk_jre test need jdk to comiple test. That is if there is no jdk, test will fail. When will jdk11u builds have jre image available? I mixed up jdk11 and jdk11u. And enabled the test as JDK11 builds have jre image. If it takes time I will re-disable it.

Hmm, you're right our pipeline did not build a jdk and a separate jre.  I assume the test pipeline expects one of each?

**Comment by sophia-guo** [comment]
As there is a growing requirement for JRE image we suppose that build will produce both jdk and jre image?

**Comment by karianna** [comment]
The JRE will go away at some point. We're only actually able to build it for 11 because OpenJDK left a legacy 'make JRE' target.  But that could get taken away anytime from 12+.  Is it possible to skip those tests if no JRE is detected?

**Pull request merged**
