### PR TITLE
Change date -R for JOBSTARTTIME to use a more compatible format

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Change to use a more compatible equivalent:
```
LC_TIME=C date +"%a, %d %b %Y %T %z"
```

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Test Grinder on various platforms:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5569/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5570/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5571/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5572/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5573/

**Comment by andrew-m-leonard** [comment]
Fixes #2127

**Comment by andrew-m-leonard** [comment]
and an Abort one on Windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5575/console

**Review by smlambert — APPROVED** [review]
Thanks for the quick response time and Grinders to verify @andrew-m-leonard 👍

**Pull request merged**
