### PR TITLE
Add jdk_vector for jdk16+

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
The test took 45mins on xlinux, so add it in extended
openj9: https://ci.eclipse.org/openj9/job/Grinder/1525/
hotspot: https://ci.adoptopenjdk.net/job/Grinder/6718/

**Comment by llxia** [comment]
Additional openj9 tests are in https://github.com/eclipse/openj9/issues/10627#issuecomment-777801473

**Review by smlambert — APPROVED** [review]
thanks @llxia !

**Comment by Mesbah-Alam** [comment]
Looks like all the testing was done using JDK16. Have we run any tests using JDk17?

**Comment by llxia** [comment]
I am not sure we need JDK17 testing as it is WIP. It does not have green sanity.openjdk build yet. 
This PR is to enable the test. If there is any failure in JDK17, then it is a defect in the product.

**Review by Mesbah-Alam — APPROVED** [review]
LGTM

**Pull request merged**
