### PR TITLE
SCM test job's property information

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Initial version.  Different directory or level test job need to pass in its own TARGET. Suppose test build job is triggered by upstream build job for now. Later we may trigger the test jobs the same way as jdk builds are triggered.

**Comment by smlambert** [comment]
Would you mind to name the templates with all lowercase characters, much like the builds are named?  so openjdk8_linux  ...  FYI, I have put a page up describing how we will name the builds here: https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Naming-Convention-for-Test-Builds-in-Jenkins

**Comment by sophia-guo** [comment]
@smlambert , rename to openjdk8_x86-64_linux. Omit the "impl" and "jobtype" part as it is a template.

**Comment by smlambert** [comment]
Updates look good.

**Pull request merged**
