### PR TITLE
WIP:  Add Liberty Startup Benchmarks

### PR DESCRIPTION
**Pull request by piyush286**
- Supported scenarios for Startup runs: AcmeAir, Cognos, DayTrader, DayTrader7, HugeEJB, HugeEJBApp, SmallServlet, TradeLite

Signed-off-by: Piyush Gupta <piyush286@gmail.com>

### CODE REVIEW

**Comment by piyush286** [comment]
I'll be adding other files such as `playlist.xml` and `build.xml` in other PR after making and testing those changes.

**Comment by smlambert** [comment]
The preference is to include the playlist & build files in the same PR, so we can test before merging the scripts.  (Same holds true for all benchmark subdirectories that are in plan).

**Comment by smlambert** [comment]
@piyush286 - also, for your awareness, we are holding off on merging anything into this repo until the release we are in the middle of is completed (so several more days).  This gives some additional time to augment this PR with the files that will allow us to verify that things run as expected.

**Comment by piyush286** [comment]
@smlambert Thanks for letting me know about it. This PR won't have any side effects since we haven't enabled Liberty (no playlist.xml or build.xml yet) so you can merge this if you want. I was planning to make small changes in each PR in order to avoid having one large PR, which would be harder to review. 

> we are holding off on merging anything into this repo until the release we are in the middle of is completed (so several more days)

I wonder whether it would be useful to have another branch, which doesn't accept any changes (or selected changes for critical issues) during release time, so that development can continue on the master branch especially if we are going to have more frequent releases, each taking a couple of days. Though we would need some mechanism to update that branch as we want (Enable or disable merging from master to that branch) and use that branch in all our Jenkins Projects. Just my two cents :)

**Comment by smlambert** [comment]
We do not normally block merging, this happens for a period of a few days every 6 months. 
 I do not wish the overhead of managing other branches (besides master) for the infrequency of this delay.

Besides, development can continue, directly out of your branch.  We specifically have created Jenkins jobs that can load from developer branches so there is no disruption to the team.

**Comment by piyush286** [comment]
@smlambert Sorry for the delay! I was held up with some other work. As requested, I've add all the files to run Liberty and tested the changes.

**Comment by smlambert** [comment]
hi @piyush286, let's discuss via webex this week, there are a number of changes that are needed for this PR.

**Comment by smlambert** [comment]
From our conversation, we agree that we need to ensure this addition can be run in the open.  At present, this PR references a zip file from an internal source, which will need to be updated to pull material from the open.

In a separate PR, I will remove the odm folder as it likely added confusion, since it references a non-open package.  It was added temporarily for some testing, but will be removed until such a time we can open-source that suite.  

I also created https://github.com/AdoptOpenJDK/openjdk-tests/issues/1112 to solicit broader feedback from the community and to start collecting the locations of open benchmark material.  

Which open material can we pull to run the LibertyStartupDT test target?

**Comment by piyush286** [comment]
Our conversation was really useful. Sorry that I wasn't aware of the whole story. That ODM and JCK did add to the confusion a bit but now it makes sense. So thank you for clarifying that :) It would be useful for us to discuss what we should prioritize in future. 

I'll continue working on this PR and add support for Open Liberty (https://github.com/OpenLiberty/open-liberty) with DayTrader (i.e. LibertyStartupDT) so that we can directly fetch all binaries from the open.

**Comment by smlambert** [comment]
Wonderful, thank you @piyush286 !  I will add you to the list of people who can launch Grinders at Adopt as well, so you can verify that your new test target works as expected.  (let's verify you have access next time we talk).  :)

**Comment by piyush286** [comment]
Closing this issue since I'm not adding WAS Liberty for now. Opened another one for Open Liberty.

**Pull request closed without merging**
