### PR TITLE
Added additional TIME_LIMIT parameter for Jenkins parallel running

### PR DESCRIPTION
**Pull request by LongyuZhang**
- added additional TIME_LIMIT parameter for pareallel running in JenkinsfileBase
[ci skip]

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
reviewers @llxia

**Comment by llxia** [comment]
Thanks @LongyuZhang

On second thought, we should avoid using `env` when unnecessary. In this case, we can just use `TIME_LIMIT`.

**Comment by LongyuZhang** [comment]
> Thanks @LongyuZhang
> 
> On second thought, we should avoid using `env` when unnecessary. In this case, we can just use `TIME_LIMIT`.

The env has been removed as suggested. Thanks.

**Comment by llxia** [comment]
Tested internally.

**Pull request merged**
