### PR TITLE
WIP: Issue #81 Enable test build on arm64

### PR DESCRIPTION
**Pull request by sophia-guo**
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_arm64_linux/3/consoleFull

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Jenkin crushed. New build:
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_test_arm64_linux/2/console

**Comment by smlambert** [comment]
@sophia-guo apologies, I lost track of this review request.  I believe @gdams mentioned yesterday that he could wrangle us up a test machine to get this test build live.

**Comment by karianna** [comment]
Looks like merge clash...

**Comment by sophia-guo** [comment]
I believe we had some arm test machine 'label' problems and some tests hang problem. PR is obsolete. @gdams when machine is ready, I will update.

**Pull request closed without merging**
