### PR TITLE
Temporarily increase verbosity on curl for SDK fetch

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Add check for env variable VERBOSE_CURL which
  will change the default -s option to -v.
- Set VERBOSE_CURL for Jenkins builds temporarily
  in order to debug issue below.

Issue eclipse/openj9#8343

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@llxia I added the option but enabled it for Jenkins builds only. This way anyone running get.sh outside of Jenkins will still get default `-s`

Here is my test build https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/5566/console
```
00:01:41.469  get jdk binary...
00:01:41.469  curl -OLJSkv --user ****:**** https://XXX/OpenJ9-JDK11-x86-64_linux-20200122-120551.tar.gz
00:01:41.469    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
00:01:41.469                                   Dload  Upload   Total   Spent    Left  Speed
00:01:41.469  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to XXX port 443 (#0)
00:01:41.469  *   Trying 169.46.35.50...
00:01:41.469  * Connected to XXX (169.46.35.50) port 443 (#0)
00:01:41.469  * Initializing NSS with certpath: sql:/etc/pki/nssdb
00:01:41.469  * skipping SSL peer certificate verification
00:01:41.469  * SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
00:01:41.469  * Server certificate:
00:01:41.469  * 	subject: CN=*.XXX,O=International Business Machines Corporation,L=AUSTIN,ST=Texas,C=US
00:01:41.469  * 	start date: Aug 07 00:00:00 2019 GMT
00:01:41.469  * 	expire date: Oct 13 12:00:00 2021 GMT
00:01:41.469  * 	common name: *.XXX
00:01:41.469  * 	issuer: CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
00:01:41.469  * Server auth using Basic with user ****
00:01:41.469  > GET /artifactory/XXX/OpenJ9-JDK11-x86-64_linux-20200122-120551.tar.gz HTTP/1.1
00:01:41.469  > Authorization: Basic 
00:01:41.469  > User-Agent: curl/7.29.0
00:01:41.469  > Host: XXX
00:01:41.469  > Accept: */*
00:01:41.469  > 
00:01:41.469  < HTTP/1.1 200 OK
00:01:41.469  < Date: Wed, 22 Jan 2020 19:40:08 GMT
00:01:41.469  < Content-Type: application/x-gzip
00:01:41.469  < Content-Length: 213843877
00:01:41.469  < Connection: keep-alive
00:01:41.469  < Server: Artifactory/6.12.3
00:01:41.469  < X-Artifactory-Id: XXX
00:01:41.469  < X-Artifactory-Node-Id: XXX
00:01:41.469  < Last-Modified: Wed, 22 Jan 2020 17:36:19 GMT
00:01:41.469  < ETag: XXX
00:01:41.469  < X-Checksum-Sha1: e9a87a13a812024874bc61cacfcc8fa5f077cf29
00:01:41.469  < X-Checksum-Sha256: 7a27c1bc974a2f95875b01d09bd311d186fe9b9921f63dbf5bb38ed57a510703
00:01:41.469  < X-Checksum-Md5: 7e7508c2630efb7657a72588da721762
00:01:41.469  < Accept-Ranges: bytes
00:01:41.469  < X-Artifactory-Filename: OpenJ9-JDK11-x86-64_linux-20200122-120551.tar.gz
00:01:41.469  < Content-Disposition: attachment; filename="OpenJ9-JDK11-x86-64_linux-20200122-120551.tar.gz"; filename*=UTF-8''OpenJ9-JDK11-x86-64_linux-20200122-120551.tar.gz
00:01:41.469  < Strict-Transport-Security: max-age=31536000; includeSubDomains
00:01:41.469  < X-XSS-Protection: 1; mode=block
00:01:41.469  < X-Content-Type-Options: nosniff
00:01:41.469  < X-Frame-Options: SAMEORIGIN
00:01:41.470  < Cache-Control: max-age=14400, must-revalidate
00:01:41.470  < Content-Security-Policy: default-src https: 'unsafe-inline' 'unsafe-eval'; font-src https: data:; img-src http: https: data:
00:01:41.470  < 
00:01:41.470  { [data not shown]
00:03:32.066  
  0  203M    0 31946    0     0  79580      0  0:44:47 --:--:--  0:44:47 79467
  1  203M    1 3424k    0     0  2434k      0  0:01:25  0:00:01  0:01:24 2433k
...
 99  203M   99  202M    0     0  1881k      0  0:01:51  0:01:50  0:00:01 2117k
100  203M  100  203M    0     0  1882k      0  0:01:50  0:01:50 --:--:-- 2118k
00:03:32.066  * Connection #0 to host XXX left intact
00:03:32.066  curl: Saved to filename 'OpenJ9-JDK11-x86-64_linux-20200122-120551.tar.gz'
00:03:32.066  unzip file: OpenJ9-JDK11-x86-64_linux-20200122-120551.tar.gz ...
```

**Comment by llxia** [comment]
Will merge after 0.18.1

**Comment by llxia** [comment]
Could you rebase and fix the conflict? Thanks.

**Comment by AdamBrousseau** [comment]
@llxia merge conflicts resolved.

**Pull request merged**
