### PR TITLE
Reinstate ConcurrentLoadTest

### PR DESCRIPTION
**Pull request by lumpfish**
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>

### CODE REVIEW

**Comment by lumpfish** [comment]
Test runs:

jdk11

hotspot
x86-64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4144
ppc64_aix_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4147
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4149

openj9
x86-64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4150
ppc64_aix_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4151
x86-64_windows: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4152

jdk15

hotspot
x86-64_mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4153
s390x_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4154
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4155

openj9
x86-64_mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4157
s390x_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4158
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4159

**Comment by lumpfish** [comment]
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/87

**Review by smlambert — COMMENTED** [review]
thanks @lumpfish - can youy please also remove comment on line 86 ?

**Comment by lumpfish** [comment]
Comment removed.  Well spotted!

**Review by smlambert — APPROVED** [review]

**Pull request merged**
