### PR TITLE
[WIP] For PR pull build testing

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by karianna** [comment]
@sophia-guo So we don't touch this PR right? :-)

**Comment by sophia-guo** [comment]
right, just for PR pull trigger build testing :)

**Comment by tellison** [comment]
Safer to mark the title as [WIP] since that will be recognized by Github too.

Not sure if you want this accepted for continuous testing, or as a one-off.  I'll assume one-off for now.

FWIW I'm not keen on the phrase `Signed-off-by:`, that sounds a bit formal.  We'll allow any group member to approve a PR simply by comment, which is traditionally LGTM.  I don't want folks to get the impression that there is a signatory role here.

**Comment by tellison** [comment]
@adoptopenjdk-github-bot test this please

**Pull request closed without merging**
