### PR TITLE
Update tck tests from extended to sanity

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
@sophia-guo thanks!  will you switch the other external tests over to extended in a separate PR (in this swap that we are doing)?

**Comment by sophia-guo** [comment]
@smlambert did you mean all others should be switched to extended?  Just to confirm.

**Comment by smlambert** [comment]
Yes, I was thinking to do that (at least shift some the others to extended).  Mostly this is an exercise in measuring how much available machine time we have nightly.  

My suggestion would be:

functional -> special
system -> special

the 3 mp-tck targets -> sanity

scala -> extended
elasticsearch -> extended
derby -> extended
lucene-solr -> extended
jenkins -> extended
wildfly -> extended
tomcat -> extended

What do you think?

**Comment by sophia-guo** [comment]
@smlambert updated. The jobs under test_external will also be updated.

**Pull request merged**
