### PR TITLE
Add x86-64_linux_mixed in openjdk_tests

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
FYI @AdamBrousseau

**Comment by renfeiw** [comment]
tested in internal grinder: Grinder/12384

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
Related to https://github.com/eclipse/openj9/issues/9231

**Pull request merged**
