### PR TITLE
if RELEASE_TAG is set checkout RELEASE_TAG

### LINKED ISSUE #2006: OpenJDK tests ignore RELEASE_TAG value
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/62/rebuild/parameterized has RELEASE_TAG=openj9-0.23.0 passed in, but we git clone `openj9` branch

```
git clone --depth 1 -q -b openj9 https://github.com/ibmruntimes/openj9-openjdk-jdk8 openjdktemp
```
It looks like instead of using `RELEASE_TAG`  value, we are using `JDK_IMPL` value.

Suspect there is a bug in https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix #2006 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by llxia** [comment]
Do we use `RELEASE_TAG ` for something else in the test pipeline? If not, should we set JDK_BRANCH to `RELEASE_TAG ` value `${buildConfig.SCM_REF}` at upstream script?
https://github.com/AdoptOpenJDK/openjdk-build/blob/a37d55290568c70fe07914609ddd639c3407bc7d/pipelines/build/common/openjdk_build_pipeline.groovy#L191

https://github.com/AdoptOpenJDK/openjdk-build/blob/a37d55290568c70fe07914609ddd639c3407bc7d/pipelines/build/common/openjdk_build_pipeline.groovy#L112

In this way, we will reduce one parameter from the test pipeline.

**Comment by sophia-guo** [comment]
For upstream trigger story we don't need extra RELEASE_TAG( JDK_BRANCH is enough). It is only used when user want to run a grinder with specific RELEASE_TAG without explicitly set JDK_REPO and JDK_BRANCH. Though we may remove that part of logic later if JDK_REPO and JDK_BRANCH is changed to be required variable.

**Comment by smlambert** [comment]
I would like to see JDK_REPO and JDK_BRANCH explicitly set by upstream jobs (that way we can remove convoluted logic used to guess which of very many options we should use based on JDK_IMPL and JDK_VERSION and/or other things).

**Comment by sophia-guo** [comment]
closed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2166

**Comment by llxia** [comment]
PR AdoptOpenJDK/openjdk-build#2166 sets OPENJ9_BRANCH, but it does not fix this OpenJDK issue. The fix for this OpenJDK issue could be similar.

**Pull request closed without merging**
