### PR TITLE
Using apt-get install ant for derby.

### LINKED ISSUE #952: External derby tests error '/derby/build.xml:212: Compiler level must be Java 9 or later.'
External derby tests error '/derby/build.xml:212: Compiler level must be Java 9 or later.'

```
08:51:43 Buildfile: /derby/build.xml
08:51:45 
08:51:45 clean:
08:51:45 
08:51:45 cleangenerated:
08:51:45 
08:51:45 cleanstate:
08:51:45 
08:51:45 cleanreleasefiles:
08:51:45 
08:51:45 clobber:
08:51:45 
08:51:45 BUILD SUCCESSFUL
08:51:45 Total time: 1 second
08:51:45 Buildfile: /derby/build.xml
08:51:47 
08:51:47 checkCompilerLevel:
08:51:47 
08:51:47 BUILD FAILED
08:51:47 /derby/build.xml:212: Compiler level must be Java 9 or later.
08:51:47 
08:51:47 Total time: 1 second
08:51:47 Buildfile: /derby/build.xml
```

https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_j9_externaltest_x86-64_linux/345/consoleFull

### PR DESCRIPTION
**Pull request by sophia-guo**
ant version is 1.10.3, derby test ask for 1.10.2 and up

Close #952 

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Grinder https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/149/

**Comment by smlambert** [comment]
hmm, I just merged this, but wondering what the behaviour will be against jdk8, skipped test, so 0 tests run, therefore fail?  we will see I guess when we break these out into individual jobs

**Comment by sophia-guo** [comment]
Depends how we will break them. For parallel the new change @renfeiw set it as pass if there is 0 tests. If manually set up each external test as a test job a test job named as jdk8_***_derby_*** should not set up. Both should not be an issue. However if we do have a test job with only one testname and later disabled by <disabled> it will fail.

**Comment by sophia-guo** [comment]
@ShelleyLambert I just happened to run into the case and found the build will definitely fail for cases with parallel and cases with <disabled>. However it failed at even early stage for current story.

The case is when there is only one testcase in playlist under the build_list folder and the testcase is either disabled or labeled with specified subset running with a different subset( parallel).

Build failed at the beginning of build stage as there is no target generated.

```
18:17:04  make[1]: Entering directory '/home/jenkins/workspace/Grinder_Sandbox/openjdk-tests'
18:17:04  make[1]: autoGen.mk: No such file or directory
18:17:04  make[1]: *** No rule to make target 'autoGen.mk'.  Stop.
18:17:04  make[1]: Leaving directory '/home/jenkins/workspace/Grinder_Sandbox/openjdk-tests'
18:17:04  settings.mk:271: recipe for target 'compile-..' failed
18:17:04  make: *** [compile-..] Error 2
```

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/171/
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/169/

**Pull request merged**
