### PR TITLE
Add Chinese data to MBCS_Tests

### LINKED ISSUE #1580: Add Chinese data to MBCS_Tests
MBCS_Tests currently supports Japanese and Korean data.
I will add Chinese data to MBCS_Tests.  Also, I will add new test cases to MBCS_Tests.

### PR DESCRIPTION
**Pull request by KKES335**
Fixes #1580 
Signed-off-by: Kentaro Kuramochi kkes335@jp.ibm.com

### CODE REVIEW

**Comment by KKES335** [comment]
Summary for the changes is as follow.

- Add Chinese data

- Add new testcases (language_tag and property_utf8)

- minor updates for easy maintenance

Here are test_grinder results with JDK 11.0.6.
Linux 
371 tests, 83 ok, 0 not ok, 288 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/37/tapResults/
AIX
371 tests, 216 ok, 0 not ok, 155 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/36/tapResults/
Windows
371 tests, 82 ok, 0 not ok, 289 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/34/tapResults/

**Comment by KKES335** [comment]
@smlambert Thank you for your comment.  The binary files for Chinese are intentional.  The File testcase needs them. The Binary files for JP/KR are already used.
But we will try to remove binary files.  I think It will take a little time.

**Comment by smlambert** [comment]
One potential option is to upload them to a public server (perhaps as part of a separate dependency job on ci.adoptopenjdk.net), then pick them up in a "getMBCSTestData" target in the build.xml file.

Example of picking up a jar file hosted on a public server, see ["getDacapoSuite" target](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/perf/dacapo/build.xml#L29-L35)

For hosting the files, we could create a job similar to https://ci.adoptopenjdk.net/view/all/job/test.getDependency/ and https://ci.adoptopenjdk.net/view/all/job/systemtest.getDependency/ called mbcs.getDependency (or some similar name).

**Comment by KKES335** [comment]
I've removed binary files.

Here are test_grinder results with JDK 11.0.6.
Linux
371 tests, 83 ok, 0 not ok, 288 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/38/tapResults/
AIX
371 tests, 216 ok, 0 not ok, 155 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/39/tapResults/
Windows
371 tests, 82 ok, 0 not ok, 289 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/41/tapResults/

**Pull request merged**
