### PR TITLE
Enhance PARALLEL=Iteration

### PR DESCRIPTION
**Pull request by llxia**
- Enhance PARALLEL=Iteration to allow users to run the test in x
parallel runs with y iterations in each run
- rename Iteration to NodesByIterations

Resolve: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1985
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
| PARALLEL | NUM_MACHINES| ITERATIONS | Grinder|
|--|--|--|--|
|NodesByIterations|2|3|[Grinder/1097](https://ci.eclipse.org/openj9/view/Test/job/Grinder/1097/)|
|NodesByIterations|empty|empty|[Grinder/1098](https://ci.eclipse.org/openj9/view/Test/job/Grinder/1098/)|

**Comment by llxia** [comment]
This PR contains testJobTemplate change. The script will need to be approved at Adopt Jenkins.

**Review by smlambert — APPROVED** [review]
LGTM @llxia!  

I can update the wiki (which looks quite stale: https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins), do you know if there is other documentation that needs updating with this PR?

**Comment by smlambert** [comment]
Script approval done.

**Comment by llxia** [comment]
> do you know if there is other documentation that needs updating with this PR?

Not sure if we have any other docs that need to be updated. I will update the description in all Grinders.

**Pull request merged**
