### PR TITLE
Add RISC-V support to OpenJDK test suites

### PR DESCRIPTION
**Pull request by ChengJin01**
Signed-off-by: Cheng Jin <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
Note: the value of SPEC  uses `riscv-64` instead of `riscv64`. 
If we agree to change to riscv64, then https://github.com/AdoptOpenJDK/TKG/blob/master/src/org/openj9/envInfo/JavaInfo.java needs to be updated to support this.
```
public String getSPEC() {
 ...
        String model = System.getProperty("sun.arch.data.model");
        System.out.println("System.getProperty('sun.arch.data.model')=" + model + "\n");
        if (Integer.parseInt(model.trim())==64) {
            spec += "-64"; <----- to be updated for riscv64
            spec = spec.replace("arm-64", "aarch64");
        }
```

Reviewer: @llxia 

FYI: @ShelleyLambert , @sxa

**Comment by ChengJin01** [comment]
the SPEC for `RISC-V` has changed to `riscv64 `to align with the naming of buildspec in OpenJ9.

**Comment by llxia** [comment]
Could you test this PR with https://github.com/AdoptOpenJDK/TKG/pull/83/ using Grinder_TKG on any platform? Thanks

**Comment by ChengJin01** [comment]
> 
> 
> Could you test this PR with [AdoptOpenJDK/TKG#83](https://github.com/AdoptOpenJDK/TKG/pull/83) using Grinder_TKG on any platform? Thanks

Launched at `Test_grinder/job/Grinder_TKG/632` with the changes at https://github.com/AdoptOpenJDK/openjdk-tests/pull/1832 & https://github.com/AdoptOpenJDK/TKG/pull/83/

**Comment by llxia** [comment]
The above Grinder failed because of missing test image. Relaunched at Grinder_TKG/640

**Pull request merged**
