### PR TITLE
Set failonerror to be true if build_image target fails

### LINKED ISSUE #2173: external/jenkins failed with 'Unable to find image 'adoptopenjdk-jenkins-test:11-jdk-ubuntu-hotspot-full' locally
It's intermittent. Happened to openj9 and hotspot:

Unable to find image 'adoptopenjdk-jenkins-test:11-jdk-ubuntu-hotspot-full' locally

https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.external_x86-64_linux_jenkins/26/console
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.external_x86-64_linux_jenkins/29/console

```
00:57:30  jenkins_test_0_FAILED
00:57:30  
00:57:30  Error: No such image: adoptopenjdk-jenkins-test:8-jdk-ubuntu-openj9-full
00:57:30  "/home/jenkins/workspace/Test_openjdk8_j9_extended.external_x86-64_linux_jenkins/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_extended.external_x86-64_linux_jenkins/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
```

The reason is image is not built successfully and marked as successful.

```
06:39:12       [exec] Step 8/21 : RUN apt-get update 	&& apt-get install -y --no-install-recommends git maven 	&& rm -rf /var/lib/apt/lists/*
06:39:12       [exec]  ---> Running in 1a20d5e5b650
06:39:12       [exec] no status provided on response: unknown
06:39:12       [exec] Result: 1
06:39:12  
06:39:12  dist:
06:39:12       [copy] Copying 2 files to /home/jenkins/workspace/Test_openjdk11_hs_extended.external_x86-64_linux_jenkins/jvmtest/external/jenkins
06:39:12  
06:39:12  BUILD SUCCESSFUL
06:39:12  Total time: 46 seconds
06:39:12  0
```

### PR DESCRIPTION
**Pull request by sophia-guo**
Close #2173 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Tested by setting the wrong github_url in set_set_info()

https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/214/console

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
@AdoptOpenJDK/tsc - plan to merge this today (prior to release), as it will abort external testing if it fails to build (2-fold benefit, making it clearer for triage team what went wrong, and freeing up machine resources faster so they can be released to other testing).

**Comment by jerboaa** [comment]
@smlambert +1 from me.

**Review by karianna — APPROVED** [review]
lgtm

**Pull request merged**
