### PR TITLE
Add manual steps to run systemtest

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/AdoptOpenJDK/openjdk-tests/issues/697
Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Documented tests have been tested locally.

**Comment by llxia** [comment]
We already have wiki for this:
https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#system-tests

**Comment by Mesbah-Alam** [comment]
@llxia - oh.. cool. Then we could use that wiki you mentioned, but we need to add the missing exports there for it to work.

**Comment by llxia** [comment]
Why we need extra info? I thought we already set it base on JAVA_BIN
https://github.com/AdoptOpenJDK/openjdk-tests/blob/1114a6936698ee0cd4adb86beb95b866837ebd6d/systemtest/build.xml#L10

**Comment by Mesbah-Alam** [comment]
Actually you are right! I didn't remember we set it in the build file. Just tried the steps locally and they worked. Will close this PR without committing.

**Pull request closed without merging**
