### PR TITLE
WIP: Reenable JdiTest

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Depends on STF issue being fixed: https://github.com/AdoptOpenJDK/stf/issues/65

**Comment by smlambert** [comment]
@andrew-m-leonard - are you currently working on a fix for https://github.com/AdoptOpenJDK/stf/issues/65 ?

**Comment by andrew-m-leonard** [comment]
Not at this minute, but it is in my "todo" as it blocks reenabling jditest for jdk8

**Comment by andrew-m-leonard** [comment]
i'm thinking isIBMJvm() should only be for IBMSDK, but need to check the other 3 places that use it first...

**Comment by andrew-m-leonard** [comment]
mmm, may have to do some more work on JdiTest... it passes on XLinux, but
fails on Mac....

**Comment by smlambert** [comment]
Setting to WIP so its not inadvertently merged before its ready.

**Comment by andrew-m-leonard** [comment]
openjdk community currently state JDI is no specified as thread-safe...

**Pull request closed without merging**
