### PR TITLE
Add Push or PR test build workflow file

### PR DESCRIPTION
**Pull request by sophia-guo**
The workflow focus on test changes in openjdk-tests, which means changes related with jenkins won't be covered by this workflow.

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Depends on https://github.com/AdoptOpenJDK/run-aqa/pull/28. When https://github.com/AdoptOpenJDK/run-aqa/pull/28 is done the yaml file need to update to use run-aqa v1.

**Comment by sophia-guo** [comment]
Failures are jdk_util 8 failures. Not related with the yml file.

**Comment by sophia-guo** [comment]
This workflow works for three scenarios:

1.  User push the branch, the action will be triggered in user's personal repo ( enable action)
2. User create the PR in openjdk-tests repo, the action will be triggered in openjdk-tests
3. PR is merged to openjdk-tests

**Comment by sophia-guo** [comment]
Open to discuss, the main purpose is to ensure PR's functionality. Pick a specific test should be enough for now? That is saying we don't need to run the whole sets. Question: minimum tests set we should select? ( jdk_version, os, build_list, target)

Going forward we can get PRs labels to decide the test targets. So next step we can add the action to auto label PRs.

**Comment by smlambert** [comment]
@sophia-guo I agree that we should just take a sampling of tests as a starting point (a small target from each directory/group), then become smarter about it, by seeing which directories changed and selecting for that.

**Comment by sophia-guo** [comment]
Updated with 
Openjdk test against hotspot with running with os: [ubuntu-16.04,
macos-10.15, windows-2016],  version: [8, 15]
System test against openj9 with running with os: [ubuntu-16.04,
macos-10.15, windows-2016],  version: [8, 15]

https://github.com/sophia-guo/openjdk-tests/actions/runs/331641472

**Comment by sophia-guo** [comment]
Investigating failures on Windows.

**Review by smlambert — APPROVED** [review]
thanks @sophia-guo - as discussed today, we can finesse iteratively.  :)

**Comment by sophia-guo** [comment]
Windows issue fixed. Update pull request repo name as `github.event.pull_request.head.repo.full_name` and push repo as `github.repository`.

[action](https://github.com/AdoptOpenJDK/openjdk-tests/actions/runs/334606051) takes  1h 25 mins with each job only takes a few minutes. The longest one takes 9 mins. That is even though jobs are parallel some will still be in queue due to the runners availability.

**Comment by smlambert** [comment]
Thanks for confirming the execution times!

**Pull request merged**
