### PR TITLE
Enable download testimage for jdk8

### PR DESCRIPTION
**Pull request by sophia-guo**
related with #2264 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Rerun the build https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7235/. The new build https://ci.adoptopenjdk.net/job/Grinder/7321/consoleFull don't have the  issue `JVMJ9TI001E Agent library jvmtitest could not be opened`. Though there is a new separate issue about the segmentation error.

```
12:26:49  java.lang.ArrayStoreException
12:26:49  Unhandled exception
12:26:49  Type=Segmentation error vmState=0x00000000
12:26:49  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000033
12:26:49  Handler1=09001000A13B4E28 Handler2=09001000A13751D8
12:26:49  R0=0000000000000004 R1=0000010010049450 R2=09001000A13B88F0 R3=0000000030046D78
12:26:49  R4=0000000000B8F180 R5=00000004000D1D10 R6=0000000000000000 R7=00000000300E4678
12:26:49  R8=0000000000000029 R9=0000000008000000 R10=0000000000000001 R11=00000004000D1D7A
12:26:49  R12=0000000000000000 R13=0000010010052800 R14=00000000300E4670 R15=0000000030014100
12:26:49  R16=0000010041802FD8 R17=0000000000000001 R18=0000000000000000 R19=0000000000000000
12:26:49  R20=0000000000000001 R21=09001000A13696E0 R22=000000000040F900 R23=090000001564D5C8
12:26:49  R24=0000000030014100 R25=000000003003A4E8 R26=0000000000000000 R27=0000000000000001
12:26:49  R28=0000000000000000 R29=0000000000000047 R30=0000010041E3EFAE R31=00000000300E45D8
12:26:49  IAR=090000001553A320 LR=0900000015555C88 MSR=A00000000000D032 CTR=090000001553A278
12:26:4
```

**Comment by smlambert** [comment]
I think that test requests a core file to be created 
```
12:26:49  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TKG/output_16146196071487/cmdLineTester_jvmtitests_5/javacore.20210301.112648.32375056.0002.txt' in response to an event
```
and then expects to find the core file in order to run some tests but can not subsequently find it... 
```
12:26:49  JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder/openjdk-tests/TKG/output_16146196071487/cmdLineTester_jvmtitests_5/javacore.20210301.112648.32375056.0002.txt
12:26:49  JVMDUMP012E Error in System dump: cannot find core file: "A file or directory in the path name does not exist.". check "ulimit -Hc" is set high enough
```

Perhaps ulimit on machine is not set high enough, and we can check how this test behaves on an AIX machine at ci.eclipse.org/openj9 server.

**Review by smlambert — APPROVED** [review]
In either event, this PR fixes the fact that we should now download testimages for jdk8.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
