### PR TITLE
Replace deprecated triggers with new syntax

### PR DESCRIPTION
**Pull request by AdamBrousseau**
See https://github.com/jenkinsci/job-dsl-plugin/blob/master/docs/Migration.md#migrating-to-177

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

@llxia for review
Tested internally Test_Job_Auto_Gen_Sandbox/84

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
We should test this everywhere to ensure all the servers are running plugin version >= 1.77
- Internal hyc is 1.77
- OpenJ9 - tested and works. Can't get plugin version without admin privileges.

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
I do not have the rights to verify the plugin version or run this script at Adopt. @smlambert Could you help to verify it? Thanks

**Comment by smlambert** [comment]
Adopt is at 1.77
Screen Shot 2021-02-05 at 7 25 49 PM

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
Script approved at Adopt.

**Pull request merged**
