### PR TITLE
use local params in the loop

### PR DESCRIPTION
**Pull request by llxia**
use local params, so params get set in each iteration

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Test_Job_Auto_Gen_sandbox/38
Test_Job_Auto_Gen_sandbox/39
Grinder/7690

**Comment by llxia** [comment]
More details:

In nightly build, testJobTemplate takes params such as level, group, etc to figure out TEST_JOB_NAME (loop is used as we may generate multiple jobs based on level x group x jdk_version combination). In the recent change, we also allow user to set TEST_JOB_NAME (no loop in this case). 

TEST_JOB_NAME needs to set to empty after each iteration to support the loop case. Otherwise, with the same TEST_JOB_NAME, the script will only generate one job with wrong params (example below).

Only one job is generated even if we have `GROUPS = jck, functional`
```
LEVELS: [sanity]
JDK_VERSIONS: [11]
GROUPS: [jck, functional]
ARCH_OS_LIST: [s390x_linux_xl]
GROUP: jck
inside if GROUP: jck
EXTRA_OPTIONS: -Xfuture --enable-preview
GROUP: functional
EXTRA_OPTIONS: 
Existing items:
    GeneratedJob{name='Test_openjdk11_j9_sanity.jck_s390x_linux_xl_Nightly'}
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in  7 second
Notifying upstream projects of job completion
```

**Comment by llxia** [comment]
Grinder/7690
Test_Job_Auto_Gen_sandbox/38
Test_Job_Auto_Gen_sandbox/39

**Comment by llxia** [comment]
Test_Job_Auto_Gen_sandbox/42
Test_Job_Auto_Gen_sandbox/43
Grinder/7691
Grinder/7692

**Comment by llxia** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=562706

**Comment by smlambert** [comment]
I've done script approval at ci.adoptopenjdk.net

**Pull request merged**
