### PR TITLE
disable aot tests in jvm_compiler for openj9

### PR DESCRIPTION
**Pull request by LongyuZhang**
- openj9 does not provide aot material
- related to issue: eclipse/openj9#10992

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Grinder links to show aot tests disabled:
xlinux: https://ci.adoptopenjdk.net/job/Grinder/4269/testReport/
plinux: https://ci.adoptopenjdk.net/job/Grinder/4273/testReport/
aix: https://ci.adoptopenjdk.net/job/Grinder/4274/testReport/
Aarch_linux: https://ci.adoptopenjdk.net/job/Grinder/4275/testReport/
mac: https://ci.adoptopenjdk.net/job/Grinder/4276/testReport/
windows: https://ci.adoptopenjdk.net/job/Grinder/4277/testReport/
s390_linux: https://ci.adoptopenjdk.net/job/Grinder/4278/testReport/

**Comment by LongyuZhang** [comment]
@llxia @sophia-guo Could you review it? Thanks.

**Comment by sophia-guo** [comment]
Could also updated other version of openj9 problemlist ProblemList_openjdk**-openj9.txt?

**Comment by LongyuZhang** [comment]
> Could also updated other version of openj9 problemlist ProblemList_openjdk**-openj9.txt?

Other versions of openj9 problemlist are also updated, thanks.
jdk13: https://ci.adoptopenjdk.net/job/Grinder/4322/testReport/
jdk14: https://ci.adoptopenjdk.net/job/Grinder/4327/testReport/
jdk15: https://ci.adoptopenjdk.net/job/Grinder/4323/testReport/
jdk16: https://ci.adoptopenjdk.net/job/Grinder/4325/testReport/

**Comment by LongyuZhang** [comment]
Will close this PR now, since we will do it after being able to disable folders. Thanks.

**Pull request closed without merging**
