### PR TITLE
Update download latest sdk from adoptopenjdk API

### PR DESCRIPTION
**Pull request by sophia-guo**
Use curl to download latest sdk from adoptopenjdk API
Add return check by download sdk name

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
This assumes curl is available on all machines, which it could be, I am not sure.  wget was added to the prereqs list and is in ansible scripts, etc.  you could keep a function called getSDK, and use curl if it is present, if not fallback to wget.  I recognize that we need to use curl for z/OS, and it is likely sufficient for all other platforms, but should we consider a fallback plan?  

This PR then would imply we change our Prerequisites.md doc, if we no longer require wget (though I think we still do require it inside of build.xml files)

**Comment by sophia-guo** [comment]
Yeah, didn't realize our prerequisites issue as [adoptOopenJDK](https://github.com/AdoptOpenJDK/openjdk-api) suggests curl. 
The hidden issue is if there is no latest sdk available  "wget https://api.adoptopenjdk.net/$JVMVERSION/$SDK_RESOURCE/$PLATFORM/latest/binary" won't return error code(non-zero), which fail the test build at later stage. A little bit annoying for debugging failures.

**Comment by llxia** [comment]
> which fail the test build at later stage.

What is the current behavior? Will it fail at unzip?

**Comment by sophia-guo** [comment]
Yes, un-tar should have problem.

**Comment by sophia-guo** [comment]
The other choice is to check the size of sdk, which is just  not straightforward. Though should work.

**Comment by smlambert** [comment]
What I was suggesting is that we use curl for all cases (not just adopt nightly & release URLs), unless we find that curl is not present on the machine, in which case attempt to fall back to use  wget.  

We can talk about it, I will not block this PR if we would want to investigate the proposal to use curl for all cases as another PR.  What you have in this PR is a dependency on curl (which we have not documented), our prereqs list only mentions wget (so we may need to update that).

**Comment by sophia-guo** [comment]
Temporarily change it to WIP as this is not a blocking issue, which only give accurate error information if there is no nightly sdk. It's not a fix of #380  .

**Comment by sophia-guo** [comment]
Rebase and retested  on arm64 and xlinux [ personal build 640-645](https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/644/).  Checked infrastructure curl is used as a base tool to configure other prerequisites.

**Comment by llxia** [comment]
Just double check, curl is available on all machines? This script is used across sites (adopt, openj9 and internal).

**Comment by smlambert** [comment]
If we are to believe what we are told, all projects use the ansible scripts at Adopt, so in theory if its present in the ansible scripts, it should be present on all machines.

**Pull request merged**
