### PR TITLE
get pre-staged jars from test.getDependency build

### PR DESCRIPTION
**Pull request by llxia**
Issue: #446

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
- Jenkins job `test.getDependency` runs daily at midnight: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test.getDependency/

- Tested with jdk_math: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox2/236/

- Tested with invalid build name. Test should continue if the build does not exist. https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox2/235/

**Comment by sophia-guo** [comment]
The point of pre-stage is in case that third-party web is unstable( I believe here especially asmtools from https://ci.adoptopenjdk.net). However if ci.adoptopenjdk.net is down like last weekend with per-staged  [test.getDependency](https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test.getDependency/)  all the Artifacts can not be accessed.

**Comment by smlambert** [comment]
I assumed the point was that the other sites (in the getDependency.pl script) were unstable.  If you also want to protect against ci.adoptopenjdk.net being down, then the url for the test.dependency job should be a parameter that defaults to ci.adoptopenjdk.net, but we can override with the ci.eclipse.org/openj9 job.

**Comment by sophia-guo** [comment]
Unrelated issue, seems your tests are running on AIX build machine with labeled `test` https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-1/ @ShelleyLambert is that machine for test so we can enable tests on AIX?

**Comment by smlambert** [comment]
Answer to the AIX question, I have enabled "weekly" tests on AIX build machine.  Though I need to change the job config to use Jenkinsfilebase instead of the personal file (as that seems to reset to use wrong params), if possible (though there is no upstream job and job number, they are triggered on a schedule).

**Comment by sophia-guo** [comment]
I believe by now it only happens to asmtools from Adopt twice. I haven't heard any issue with other libs.  However, it may happen to others later.

@llxia mentioned "Ideally, getDependency job should only be called when functional test is invoked. If system test needs similar job, it should be created separately" in that case could we limit this step to function tests, i.e. only run this step when target is functional?
I

**Comment by sophia-guo** [comment]
Thanks @ShelleyLambert I recalled the story of AIX.

**Comment by llxia** [comment]
Yes, this work is mainly for OpenJ9 Jenkins test jobs. For AdoptOpenJDK Jenkins test jobs, we are at least protected from other unstable sites like Shelley mentioned.

**Comment by llxia** [comment]
>"Ideally, getDependency job should only be called when functional test is invoked. If system test needs similar job, it should be created separately" in that case could we limit this step to function tests, i.e. only run this step when target is functional?

That is our long term goal, which needs a bit more work to be done in build.xml files https://github.com/eclipse/openj9/issues/1708
Currently all tests runs getDependency perl before compilation in make. I can limited the script to run copyArtifacts for just functional target, but current solution protects other component tests as well.

**Pull request merged**
