### PR TITLE
Convert subset to version

### PR DESCRIPTION
**Pull request by renfeiw**
- using version in playlists

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=system --target=special --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list= functional --target=special --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Comment by renfeiw** [comment]
run aqa --sdk_resource=nightly --build_list=functional --target=special --platform=x86-64_linux --jdk_version=11 --jdk_impl=openj9

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
thanks @renfeiw !

**Comment by smlambert** [comment]
DDRtests are failing to compile in the checks, have not looked closely at why, but know that it is not related to this PR, so will merge.

**Pull request merged**
