### PR TITLE
Change jdk_math_jre to special level

### PR DESCRIPTION
**Pull request by sophia-guo**
Make sure jre test is available for jre JDKs.

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Will also create necessary build for special target and setup the build trigger in upstream build( openjdk-build).

**Comment by sophia-guo** [comment]
Originally we'd like to enable it for all jdk_version as default. At some point new JDK11 build do not have jre sdk. And was told jre image won't be built since JDK12+.

> As there is a growing requirement for JRE image we suppose that build will produce both jdk and jre image?

https://github.com/AdoptOpenJDK/openjdk-tests/pull/701#issuecomment-441775333

> The JRE will go away at some point. We're only actually able to build it for 11 because OpenJDK left a legacy 'make JRE' target. But that could get taken away anytime from 12+. Is it possible to skip those tests if no JRE is detected?

https://github.com/AdoptOpenJDK/openjdk-tests/pull/701#issuecomment-441779721

Just check it is build at least in JDK13 build. So probably we need to double check it again as the story may change?

**Comment by smlambert** [comment]
@karianna @johnoliver - per @sophia-guo comment above, where do we stand with enabling jre testing on all jdk versions?  its enabled for jdk8-10 (not 11+ though we see jre is being built for jdk13).

**Comment by smlambert** [comment]
I will merge, we can update subsets later once we get more information.

**Pull request merged**
