### PR TITLE
Remove hidden class test excludes

### PR DESCRIPTION
**Pull request by tajila**
Remove hidden class test excludes

Remove excludes for BasicTest and TypeDecriptorTest

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
Tests are now passing https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3884/testReport/

**Comment by tajila** [comment]
@llxia please review

**Review by smlambert — APPROVED** [review]

**Review by llxia — APPROVED** [review]
LGTM

**Comment by pshipton** [comment]
There are still tests excluded under this issue on jdk16, which is out of support, but not on subsequent versions.

**Pull request merged**
