### PR TITLE
Add quakus tests

### LINKED ISSUE #1463: Add quarkus tests
This issue is to add [quarkus java testing](https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#setup) to the external test group, and put a placeholder for the native tests (if we end up tying a graalvm build into our regularly scheduled pipelines).

### PR DESCRIPTION
**Pull request by sophia-guo**
Adding quakus tests.

Close #1463

### CODE REVIEW

**Comment by sophia-guo** [comment]
Disabled quarkus-documentation tests which hung when doing:
Downloaded from central: https://repo.maven.apache.org/maven2/org/jruby/jruby-stdlib/9.2.6.0/jruby-stdlib-9.2.6.0.jar (11 MB at 3.6 MB/s)

or:
Downloaded from central: https://repo.maven.apache.org/maven2/org/jruby/jruby-core/9.2.6.0/jruby-core-9.2.6.0.jar (10 MB at 1.5 MB/s)

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1046/

Wget the jar from local only takes a second. Believe there is some other issue hidden.

**Comment by sophia-guo** [comment]
Grinder: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1049/

**Comment by sophia-guo** [comment]
Initial or most of the CS was contributed by @ShelleyLambert https://github.com/smlambert/openjdk-tests/tree/quarkus

**Comment by smlambert** [comment]
I've also launched a Grinder to verify hotspot, once its completed, I will merge this (as it will have no effect on the group of tests to be run on upcoming release (its not a stability concern).

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1050

**Pull request merged**
