### PR TITLE
standardize test project naming

### PR DESCRIPTION
**Pull request by TianyuZuo**
* all test project are named with lower-case with underscore
* change TestExample to example
* change OpenJDK_Playlist to openjdk_regression
* update old directory references to new directory name

Signed-off-by: Tianyu Zuo <tianyu@ca.ibm.com>

### CODE REVIEW

**Comment by TianyuZuo** [comment]
Reviewer: @ShelleyLambert 
Reviewer: @sophia-guo  

As discussed, change OpenJDK_Playlist to openjdk_regression and change TestExample to example. Also changed Utils to utils. 

One doubt is that if we also need to chagne Build to build, which would suite our naming standard.

**Comment by sophia-guo** [comment]
add to whitelist

**Comment by TianyuZuo** [comment]
Changed Build to buildenv to match the openj9 convention, also created issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/106 to have a history to update the Jenkins test jobs' configurations.

PR is ready for another review.

**Comment by smlambert** [comment]
What is here looks good, I added a comment on #106, to co-ordinate the changes of rename of buildenv with changes to Jenkinsfiles to avoid downtime of working builds.  (so 2 choices, include them in this PR, or wait and change buildenv in later PR with Jenkinfile changes)

**Comment by sophia-guo** [comment]
Please make sure to update all related test build configuration.

**Pull request merged**
