### PR TITLE
Exclude tomee and openliberty-mp-tck for s390x jdk8 Hotspot

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Test jobs:
 https://ci.adoptopenjdk.net/view/Test_external/job/Test_openjdk8_hs_sanity.external_s390x_linux_openliberty-mp-tck/12/

**Review by smlambert — COMMENTED** [review]
thanks @andrew-m-leonard - can you add a comment in the playlist files with a link to the issue that explains the exclusion `<!-- Exclude on hotspot under https://github.com/AdoptOpenJDK/openjdk-tests/issues/xxxxx -->`

**Comment by andrew-m-leonard** [comment]
> thanks @andrew-m-leonard - can you add a comment in the playlist files with a link to the issue that explains the exclusion `<!-- Exclude on hotspot under https://github.com/AdoptOpenJDK/openjdk-tests/issues/xxxxx -->`

thanks, added

**Comment by andrew-m-leonard** [comment]
@ShelleyLambert i'm happy with the test job invocations, if you're happy can you review please? thanks

**Review by sxa — COMMENTED** [review]
I'll let Shelley do the formal approval but I approve of this change.

**Review by smlambert — APPROVED** [review]
LGTM

**Pull request merged**
