### PR TITLE
Added Apache Camel tests into external group

### PR DESCRIPTION
**Pull request by LongyuZhang**
- added Apache Camel in the external group

issue: #1608

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test link: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2210/

**Comment by smlambert** [comment]
Thanks @LongyuZhang - can I also get you to update the common_functions.sh script (in supported_tests: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/common_functions.sh#L34
and in the case statement: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/common_functions.sh#L179)?

**Comment by LongyuZhang** [comment]
@smlambert The suggested content has been added to common_functions.sh and tested locally, thanks.

**Comment by james-crowley** [comment]
@LongyuZhang @smlambert Just noticed you guys add a new test case via the Docker framework!!!!!! This is great!

**Pull request merged**
