### PR TITLE
Set shallow to true for git clone

### PR DESCRIPTION
**Pull request by llxia**
Fixes: #1895

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Grinder/9004
-> generated child job Grinder_testList_1/91
```
 > git fetch --tags --force --progress --prune --depth=1 -- https://github.com/llxia/openjdk-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=60
```

**Comment by llxia** [comment]
Note: we will need to approve testJobTemplate file at Adopt Jenkins once this PR is merged.

**Comment by smlambert** [comment]
As we have completed all releases (for all versions and all implementations), lockdown of repos is lifted, and I will merge now (and approve script at Adopt).

**Comment by smlambert** [comment]
Script approval at Adopt completed and verified via https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3603

**Comment by AdamBrousseau** [comment]
It's probably not default because the default checkout is lightweight which is lighter and faster than a shallow clone.

Did we test to see what the disk usage is for the workspace using a shallow clone?

**Comment by AdamBrousseau** [comment]
My test shows the workspace is reduced only by a few MB to 172M so I think this solution is out :(

**Comment by AdamBrousseau** [comment]
You might be able to get this to work with a custom refspec as well as the shallow and maybe also setting the "honour refspec on initial clone" but you'd have to play around with it. The problem may be that that combination of options may not fit everyone's use case for the pipelines.

**Comment by llxia** [comment]
> It's probably not default because the default checkout is lightweight which is lighter and faster than a shallow clone.

Unfortunately, the l[ightweight default](https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.workflow.CpsScmContext.lightweight) is false.

> My test shows the workspace is reduced only by a few MB to 172M so I think this solution is out :(

what cmd did you run?

**Comment by AdamBrousseau** [comment]
I tested with a test job generated using the new shallow option. I removed the workspace on master then ran the test job and then checked the workspace usage on master.

**Comment by llxia** [comment]
ok, thanks. I do not have access to master and not able to run cmd on it through a job, so I was wondering what you did. I can play with other options, but I may need your help to check the space on the master.

**Pull request merged**
