### PR TITLE
Set --enable-preview in jck builds

### PR DESCRIPTION
**Pull request by llxia**
Set --enable-preview as default opt in jck except for JDK8

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Related: 
https://github.com/eclipse/openj9/pull/8384
runtimes/backlog/issues/230

**Comment by llxia** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=559463

**Comment by smlambert** [comment]
If you are doing script approval, we should merge https://github.com/AdoptOpenJDK/openjdk-tests/pull/1536 to (so only need 1 approval request).

**Comment by llxia** [comment]
The above request got approved already. I will create any request once #1536 is merged.

**Pull request merged**
