### PR TITLE
Add jenkins files for ppc64le and s390x docker platforms

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves: https://github.com/AdoptOpenJDK/openjdk-tests/issues/715
Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
@sophia-guo , please note that this PR has an additional change to https://github.com/Mesbah-Alam/openjdk-tests/blob/addToExternalTest_s390x_and_ppc64le_arch/buildenv/jenkins/openjdk_x86-64_linux_docker - in that I've added the the `node ("master")` here that was not added to it before.

**Comment by Mesbah-Alam** [comment]
Test for ppc64le : https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/62/console suggests : 
```There are no nodes with the label ‘ci.role.test&&hw.arch.ppc64le&&sw.os.linux&&sw.tool.docker’``` 

@sxa555 , It looks like we need to add `sw.tool.docker` label to the docker enabled ppc64le Linux machines at Adopt .

**Comment by Mesbah-Alam** [comment]
Test with x64 linux: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/63/console

**Comment by smlambert** [comment]
I will add the labels you mention @Mesbah-Alam .  For grinders, remember that you can put hostname for a label to override what the jenkins scripts default to looking for, so please do that for now.

**Comment by Mesbah-Alam** [comment]
Running directly on the ppc64le test machine `test-osuosl-ppc64le-ubuntu-16-04-1` reveals that docker has not yet been installed there: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/66/console

**Comment by Mesbah-Alam** [comment]
@AdamBrousseau , good point. We can use an existing flag `BUILD_LIST` and do something like this: 

```
if (env.BUILD_LIST == 'thirdparty_containers'){
	LABEL='ci.role.test&&hw.arch.x86&&sw.os.linux&&sw.tool.docker'
} else {
	LABEL='ci.role.test&&hw.arch.x86&&sw.os.linux'
}

node ("master") {
    checkout scm
    def jenkinsfile = load "${WORKSPACE}/openjdk-tests/buildenv/jenkins/JenkinsfileBase"
    jenkinsfile.setLabelParam()
    cleanWs()
}

stage('Queue') {
    node("$LABEL") {
        PLATFORM = 'x64_linux'
        SDK_RESOURCE = 'upstream'
        SPEC='linux_x86-64_cmprssptrs'
        checkout scm
        def jenkinsfile = load "${WORKSPACE}/openjdk-tests/buildenv/jenkins/JenkinsfileBase"
        jenkinsfile.testBuild()
    }
}
```

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/67/console

**Comment by AdamBrousseau** [comment]
```
LABEL='ci.role.test&&hw.arch.x86&&sw.os.linux'
if (env.BUILD_LIST == 'thirdparty_containers'){
	LABEL+='&&sw.tool.docker'
}
```
As long as `thirdparty_containers` will always mean docker and nothing else will ever need docker.

**Comment by Mesbah-Alam** [comment]
Actually, introduced a new Boolean flag called `DOCKER_REQUIRED`. The jenkins files will check for it. I will set it in each of the Grinders and the external test jobs at Adopt.

**Comment by smlambert** [comment]
Suggest to use a separate parameter.

BUILD_LIST can be blank, in which case all test material compiled.  Then, if test target is scala_test or some other target in thirdparty_containers, the test would try to run on SPEC not on SPEC with docker installed.

**Pull request merged**
