### PR TITLE
Enable system tests for JDK11

### PR DESCRIPTION
**Pull request by llxia**
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
fyi @Mesbah-Alam

**Comment by llxia** [comment]
I see 30+ errors like following: `Could not find test plugin called 'LayersTest' in any of these workspaces`. If these failure is due to exclusion of compilation for JDK11, we should exclude them from execution too. @Mesbah-Alam could you confirm? Do you have the issue links about these compilation exclusion, so I can add comment on the test? Thanks.

```
00:40:01 TEST TARGETS SUMMARY
00:40:01 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
00:40:01 PASSED test targets:
00:40:01 	MathLoadTest_autosimd_0
00:40:01 	MathLoadTest_bigdecimal_0
00:40:01 	NioLoadTest_0
00:40:01 	LambdaLoadTest_OpenJ9_Linux_CompressedRefs_0
00:40:01 	DaaLoadTest_daa1_0
00:40:01 	DaaLoadTest_daa2_0
00:40:01 	DaaLoadTest_daa3_0
00:40:01 	TestJlmRemoteClassNoAuth_0
00:40:01 	TestJlmRemoteMemoryAuth_0
00:40:01 	TestJlmRemoteMemoryNoAuth_0
00:40:01 	TestIBMJlmLocal_0
00:40:01 	TestIBMJlmRemoteClassAuth_0
00:40:01 	TestIBMJlmRemoteClassNoAuth_0
00:40:01 	TestIBMJlmRemoteMemoryAuth_0
00:40:01 	TestIBMJlmRemoteMemoryNoAuth_0
00:40:01 
00:40:01 FAILED test targets:
00:40:01 	ClassLoadingTest_0
00:40:01 	CpMpTest_CpMp_0
00:40:01 	CpMpTest_MP_0
00:40:01 	CpMpTest2_0
00:40:01 	CpMpTest3_0
00:40:01 	CpMpModularJarTest_0
00:40:01 	CpMpModularJarTest2_0
00:40:01 	CpMpModularJarTest3_0
00:40:01 	JDKInternalAPIsTest_0
00:40:01 	AutomaticModulesTest1_0
00:40:01 	AutomaticModulesTest2_0
00:40:01 	AutomaticModulesTest_ImpliedReadabilityTest1_0
00:40:01 	AutomaticModulesTest_ImpliedReadabilityTest2_0
00:40:01 	AutomaticModulesTest_ImpliedReadabilityTest3_0
00:40:01 	ExplicitModulesTest_0
00:40:01 	ServiceLoadersTest_0
00:40:01 	PatchModuleTest_PlatformModPatchModule_0
00:40:01 	PatchModuleTest_AppModPatchModule_0
00:40:01 	PatchModuleTest_UnexportedTypePatchModule_0
00:40:01 	PatchModuleTest_AdvancedPatchModule_0
00:40:01 	PatchModuleImageTest_PlatformModPatchModule_0
00:40:01 	PatchModuleImageTest_AppModPatchModule_0
00:40:01 	PatchModuleImageTest_UnexportedTypePatchModule_0
00:40:01 	PatchModuleImageTest_AdvancedPatchModule_0
00:40:01 	UpgradeModPathTest_ExpDirModUpgrade_0
00:40:01 	UpgradeModPathTest_ExpDirModUpgradeCRImage_0
00:40:01 	UpgradeModPathTest_JarredModUpgrade_0
00:40:01 	UpgradeModPathTest_JarredModUpgradeCRImage_0
00:40:01 	JlinkTest_RequiredMod_0
00:40:01 	JlinkTest_AddModLimitMod_0
00:40:01 	CpMpJlinkTest_0
00:40:01 	JlinkPluginOptionsTest_GeneralOptionsTest_0
00:40:01 	LayersTest_0
00:40:01 	CLTest_0
00:40:01 	CLTestImage_0
00:40:01 	CLLoadTest_0
00:40:01 	CLStressWithLayers_0
00:40:01 	CLStressWithLayersCRI_0
00:40:01 
00:40:01 TOTAL: 61   EXECUTED: 53   PASSED: 15   FAILED: 38   SKIPPED: 8
```

**Comment by Mesbah-Alam** [comment]
Hi @llxia - the failed tests are all Modularity tests. I didn't have a chance to run them on Java 11 yet. I'll run them today and debug to find out what is it that they are missing and post an update on this PR.

**Comment by llxia** [comment]
Should I deliver this change and we open issues after? I think it is better to enable the tests before we branch next friday.

**Comment by Mesbah-Alam** [comment]
@llxia - as you suspected, Modularity tests are [excluded ](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/build.xml) from compiling on Java11 due to the fact that some of these tests have to be re-implemented due to changes made in some of the Java modules in Java 11, details here: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/150. 

So, we can't enable Java 11 on the modularity tests listed above.

**Comment by Mesbah-Alam** [comment]
I saw your last comment after posting my last! 

A new issue wold effectively be a dup of https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/150. I believe a comment in https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/playlist.xml - stating that modularity tests are pending on Java 11 due to issue 150 would suffice.

**Comment by llxia** [comment]
Changeset is updated

**Pull request merged**
