### PR TITLE
Add credentials to checkout scm for AdoptOpenJDK Testing repository

### PR DESCRIPTION
**Pull request by vsebe**
Use credentials with the ssh git protocol.

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
[Test-sanity.system-JDK11-linux_ppc-64_cmprssptrs_le](https://ci.eclipse.org/openj9/view/Sandbox/job/vs_Test-sanity.system-JDK11-linux_ppc-64_cmprssptrs_le/2/console) without ADOPTOPENJDK_* parameters
[est-sanity.system-JDK11-linux_ppc-64_cmprssptrs_le](https://ci.eclipse.org/openj9/view/Sandbox/job/vs_Test-sanity.system-JDK11-linux_ppc-64_cmprssptrs_le/3/console) with ADOPTOPENJDK_* parameters

**Comment by vsebe** [comment]
@llxia please review

**Comment by llxia** [comment]
Could you run grinder with https and ssh? Thanks

**Comment by llxia** [comment]
Thanks Violeta for testing in internal Grinder.

**Pull request merged**
