### PR TITLE
Override LABEL variable when params.LABEL is passed

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- When LABEL is passed as a param, the build
  description would still use LABEL rather
  than params.LABEL. Overiding the variable
  LABEL with params.LABEL will ensure the
  right LABEL is used for the description.
- Minor formatting and whitespace fixes

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by smlambert** [comment]
I am curious to hear if you hit a case where a wrong label was used?

**Comment by AdamBrousseau** [comment]
For example
https://ci.adoptopenjdk.net/job/Grinder/1040/
I passed `LABEL:test-godaddy-win2016-x64-2` as a parameter but the description shows
```
TARGET: testOSMXBeanLocal_0
LABEL: ci.role.test&&hw.arch.x86&&sw.os.windows
test-godaddy-win2016-x64-2
```
So while in this case it is "ok" because I still get the NODE_NAME in the description, it is technically wrong because LABEL is incorrect. If I passed `LABEL:fooboo` and got the same machine above, I would expect the description to be
```
TARGET: testOSMXBeanLocal_0
LABEL: fooboo
test-godaddy-win2016-x64-2
```
But as is it will still print whatever the default is in the top level JenkinsFile.
It's a minor nit but still a bug at least imo.

**Comment by smlambert** [comment]
Ah, I understand, and agree it may confuse if we call it LABEL, but perhaps something else, like DESC as funnily enough, just tonight, Lan and I used that bug as a feature, as it allowed us to click on it to get quickly to the list of other machines that we could rerun a test on... 

Screen Shot 2019-11-08 at 12 29 45 AM

I am worried that if we make the change you are suggesting:
1) it provides redundant information in the case when someone supplies the hostname
2) we lose the feature of being able to get quickly to the list of other machines to run on

So from a UX perspective, it seems less useful to change it, than to leave it as is, but I will leave this open to discussion.

**Comment by AdamBrousseau** [comment]
1. Agree. I wonder how often does a user change the LABEL param? 
2. Agree, but only when LABEL is passed as a param. In any other build this wouldn't be the case. It would only be the Grinder use case where someone passes it.
I guess the main question is what was the original purpose or use case this was added for? Looks like #687 and #733 is the relevant issues but I don't see _why_ LABEL was added.
We could change the LABEL wording as you say but it might be more accurate to call it DEFAULT LABEL but ideally something shorter?

**Comment by smlambert** [comment]
Or not call it anything, but add HOST: in front of hostname.
Those links are there to help testers/devs triage and quick views of things, they were added to serve us as we see fit.  I think its more important to have the quick link to other machines, than seeing what label was used (which I can see when I hit rebuild).  

The most common use case is to pass in a specific hostname as a label to rerun a failing test on a particular machine.  I do not know of any other common use cases.

**Comment by AdamBrousseau** [comment]
Ok, so remove `LABEL` text in front of the default LABEL value. I think `HOST` was not added since the Adopt machines names are too long to fit on one line (https://github.com/AdoptOpenJDK/openjdk-tests/pull/733#issuecomment-445357414)

**Comment by llxia** [comment]
I merged PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1434. Please rebase and update these PPC files too. Thanks

**Comment by AdamBrousseau** [comment]
Rebased on #1434 and #1446. Removed `LABEL` text. Maybe hold off on this until a decision is made on #1445.

**Comment by karianna** [comment]
@AdamBrousseau sorry will need a rebase again.

**Comment by AdamBrousseau** [comment]
I believe this work has been inadvertently completed by #1521

**Pull request closed without merging**
