### PR TITLE
Add alpine-linux and x86-64_solaris platforms

### LINKED ISSUE #2060: Add Solaris/x64 as a supported testing platform
**Describe the bug** Unable to submit jobs to test our Solaris/X64 bulds as we do not have x86-64_solaris as a viable `PLATFORM` option in https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_tests We do have `sparcv9_solaris` but not the X64 variant

**To Reproduce** Try to run a job (e.g. a Grinder) and it's not an option for `PLATFORM`

**Expected behavior** Ability to run tests against Solaris/x64 builds

**Screenshots**

**Additional context** JDK8 / HotSpot Release Builds for Solaris/x64 are at https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot and the job that builds them is at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/

### LINKED ISSUE #2223: JDK 16 and 17 on Alpine (musl) need testing
In roughly a month, we're going to release AdoptOpenJDK 16. For the first time, support for musl instead of glibc is included. While we build nightlies, we don't test them:

https://github.com/AdoptOpenJDK/openjdk-build/blob/3a26592a68ac5d58ae55bbe385a620f29d2ce695/pipelines/jobs/configurations/jdk16_pipeline_config.groovy#L55-L65

I think we should do something about that.

### PR DESCRIPTION
**Pull request by smlambert**
Fixes #2060 
Fixes #2223 
- Add alpine-linux and x86-64_solaris platform support in testing

### CODE REVIEW

**Comment by smlambert** [comment]
Taking it out of draft, there will still need to be a change made in STF for system tests, but there is no reason to delay this from being reviewed and merged.

**Review by aahlenst — APPROVED** [review]

**Comment by sophia-guo** [comment]
@renfeiw does AUTO_DETECT JavaInfo need to be updated correspondingly? Especially alpine-linux with `os.musl`?

**Comment by renfeiw** [comment]
> @renfeiw does AUTO_DETECT JavaInfo need to be updated correspondingly? Especially alpine-linux with `os.musl`?

If the auto detected JavaInfo matches the SPEC, it should be fine. Otherwise, we need to update the JavaInfo detector or the SPEC string to make them match. 

I will also update https://github.com/AdoptOpenJDK/TKG/blob/master/resources/buildPlatformMap.properties once this PR is merged.

**Comment by smlambert** [comment]
I populated the SPEC field with 'nonsense' as @llxia mentioned that we can now remove the use of SPEC altogether (and as far as I know there is no spec file for this platform).

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2304#issuecomment-785970969
this is another case of multiple names for the same platform

The sw.os.musl label was added [here](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1929#issuecomment-783465921), I should probably correct this now to match the Jenkins label and the os that is being assigned/used in build scripts and API.

From the console output of the build, the os is 'alpine-linux'
```
08:53:44  ===METADATA OUTPUT===
[Pipeline] echo
08:53:44  {
08:53:44      "vendor": "AdoptOpenJDK",
08:53:44      "os": "alpine-linux",
08:53:44      "arch": "x64",
08:53:44      "variant": "hotspot",
08:53:44      "version": {
08:53:44          "minor": 0,
08:53:44          "patch": null,
08:53:44          "msi_product_version": "16.0.0.36",
08:53:44          "security": 0,
08:53:44          "pre": null,
08:53:44          "adopt_build_number": 0,
08:53:44          "major": 16,
08:53:44          "version": "16+36-202102231311",
08:53:44          "semver": "16.0.0+36.0.202102231311",
08:53:44          "build": 36,
08:53:44          "opt": "202102231311"
08:53:44      },
08:53:44      "scmRef": "jdk-16+36_adopt-110-gdce5f06a70d",
08:53:44      "buildRef": "openjdk-build/904ad59",
08:53:44      "version_data": "jdk16",
08:53:44      "binary_type": "jre",
08:53:44      "sha256": "573a3ad62714d408741457fcf26b161a1282b90a64d061559de67a369c26bf17",
...
```

**Comment by sophia-guo** [comment]
If `"os": "alpine-linux"` that means AUTO_DETECT JavaInfo is good ( `if (osName.contains("linux")) {spec = "linux";}`

**Review by sophia-guo — APPROVED** [review]

**Pull request merged**
