### PR TITLE
enable jck-runtime-vm-instr for JDK8

### PR DESCRIPTION
**Pull request by llxia**
Related: runtimes/backlog/issues/357 and runtimes/backlog/issues/352

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
@llxia : on a second thought, I recall @JasonFengJ9 would have preferred to have some of these vm tests in sanity instead of extended (which is why `jck-runtime-vm-instr` was put in sanity at the first place, albeit 10+). So, please keep `jck-runtime-vm-instr` as sanity. Also, we could simply not have any <subset> tag for this target -- so that it can run in 8, 11, 15.. all of them (instead of just 8)-- as the test exits in all.

**Comment by JasonFengJ9** [comment]
> have preferred to have some of these vm tests in sanity instead of extended (which is why jck-runtime-vm-instr was put in sanity at the first place, albeit 10+).

That's correct, there are some vm/lang tests running nightly to catch JCK breakage earlier.

**Comment by llxia** [comment]
Sure, that will make this change simpler.

**Comment by llxia** [comment]
Updated. Waiting for internal Jenkins to be available so I can run a Grinder.

**Comment by llxia** [comment]
Grinder/8927

**Comment by llxia** [comment]
Close this PR as the change is in #1884

**Pull request closed without merging**
