### PR TITLE
Revamped Dockerfiles for various Test Cases

### PR DESCRIPTION
**Pull request by james-crowley**
Revamped/Updated the following Dockerfiles and Test scripts:

- Derby
- Jenkins
- Kafka
- Lucene Solr
- Openliberty
- Payara
- Scala
- Thorntail
- Tomcat
- TomEE
- Wildfly
- Wycheproof

Updates include arguments for tags and versions every GitHub repo/Software package. Removal of unneeded packages, commands, parameters.

Test not updated/revamped include:

- System Test
- Functional Test
- Elasticsearch

Elasticsearch and Wycheproof are points of interest. These softwares only support x86_64 out of the bag. While building for `s390x` or other architectures are possible, it requires a lot more commands.

Additionally, most of these updated Dockerfiles need to be test for longer runs. My laptop could not do some of the longer run tests. I tested all Dockerfiles build and most tests pass, but there might be some bugs/issues in longer run tests, which I did not catch.

### CODE REVIEW

**Comment by james-crowley** [comment]
We can actually update Scala container, now that https://github.com/sbt/sbt/issues/5294 is closed. We can verify the download via hash. 

And once, https://github.com/bazelbuild/bazel/issues/10408, gets resolved we can add easy multi-arch support for Wycheproof.

**Comment by smlambert** [comment]
Launching Grinders for this PR, can I get @renfeiw or @llxia to look at this failure (related to moving TDUMPS, so likely related to recent change in TKG for z/OS core dump support).

derby/jdk11/hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1410

**Comment by smlambert** [comment]
Grinders for this PR, checkmarked if pass, comment if fail:

- [ ] derby/jdk11/hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1410 - fail, issue seems unrelated to this PR (investigating)
- [ ] jenkins/jdk8/openj9: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1412
- [ ] kafka/jdk8/hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1413
- [ ] lucene-solr/jdk11/hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1414

**Comment by llxia** [comment]
>derby/jdk11/hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1410


The real error is 
```
09:45:35       [exec] Step 18/20 : RUN git checkout ${DERBY_TAG}
09:45:35       [exec]  ---> Running in cf4d2d87166c
09:45:36       [exec] [91merror: pathspec '10.15.1.3' did not match any file(s) known to git.
09:45:37       [exec] The command '/bin/sh -c git checkout ${DERBY_TAG}' returned a non-zero code: 1
```

There is no `10.15.1.3` branch or tag in https://github.com/apache/derby repo.

I got the same error locally:
```
lans-mbp:test lanxia$ git clone https://github.com/apache/derby.git
Cloning into 'derby'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 158163 (delta 23), reused 25 (delta 22), pack-reused 158133
Receiving objects: 100% (158163/158163), 82.47 MiB | 1.14 MiB/s, done.
Resolving deltas: 100% (104123/104123), done.
Checking out files: 100% (4326/4326), done.
lans-mbp:test lanxia$ cd derby/
lans-mbp:derby lanxia$ git checkout 10.15.1.3
error: pathspec '10.15.1.3' did not match any file(s) known to git
lans-mbp:derby lanxia$
```

**Comment by smlambert** [comment]
ah, thanks for your keen eyes @llxia !  FYI @james-crowley please see Lan's comment above

**Comment by james-crowley** [comment]
@ShelleyLambert @llxia Sorry for the incorrect version. I am not sure where that number came from.

While I am updating Derby's tag/branch, I am going to update a couple others. Is there a general rule of what branch/tag you guys want to be pulling from? Is the latest release a good option for tags/branches?

**Comment by james-crowley** [comment]
For example for Jenkins, should we be pulling from the LTS, `jenkins-2.190.3`, or from the most current release, `jenkins-2.209`?

I changed it to LTS, since it is more stable and should give us more reliable test results. But what are your thoughts?

**Comment by smlambert** [comment]
LTS as default is good.  If we eventually parameterize this so its easy for devs to swap to some other version, will be nice, but let's lean towards 'more stable' choices.  :)

**Comment by james-crowley** [comment]
All the test I updated now have build args which devs can swap out. For example in the Jenkins image you can do:

```
docker build --build-arg JENKINS_TAG=<tag_name> -t adoptopenjdk-jenkins-test .
```

Which will thus check out a different tag/branch when cloning Jenkins.

**Comment by smlambert** [comment]
Rebuild grinders:

derby: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1439
openliberty: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1440
payara: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1441

**Comment by james-crowley** [comment]
@smlambert I just fixed Tomcat, TomEE and Open Liberty. Or at least I hopefully did! Could you please rerun these?

I had a question on:
```
wycheproof/jdk11/hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1438 - 03:46:41 Error: No such container:path: wycheproof:/testResults/testlogs
```

For this container, they folder `testResults` does get create in the `/` root directory. I am not sure where `testlogs` gets generated. I figure that is generated from the tests? If, so is the reason why we can't access this path is because the tests failed? If not, I am confused on why this is failing. @smlambert or @llxia have any input/ideas on this issue?

**Comment by smlambert** [comment]
For wycheproof, I will have to run locally to see what is expected behaviour (where the test logs get created, maybe something changed since this was added and we have not adapted to it).

**Comment by james-crowley** [comment]
@smlambert I am not sure if the bug that is happening with Wildfly is something I have done. I opened an issue with Wildfly to address the issue, https://issues.redhat.com/browse/WFLY-12899.

In the last push, TomEE was fixed, but Tomcat and Open Liberty both still fail. I am looking into these issues.

**Comment by james-crowley** [comment]
@smlambert or @llxia could you take a look at this, https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1605/console ? I am trying to finish the test for Wildfly. But I am getting an out of memory error. I am not sure if that an issue on my end or an issue with the server.

**Comment by smlambert** [comment]
Strange, so we see that the wildfly tests have been running consistently on a weekly basis without hitting that OOM here: https://ci.adoptopenjdk.net/view/Test_external_weekly/job/openjdk11_hs_external_extended_wildfly_x86-64_linux/ - last run on Jan 5th.

The main change in your PR to use a tagged version, 18.0.0.Final ?
I guess we should look at differences between it and latest/master, do you still hit that error when you don't pull a tagged version (but keep all other changes same?)

**Comment by james-crowley** [comment]
@smlambert Just want to recap the test we have left. 

- **Jenkins** 
    - > un completes, fails with OOM, jdk8/openj9 has very low default memory, to be equivalent to hotspot default, need to set different -Xmx for openj9
    - Is that something you are handling?

- **openliberty**
    - It is still something I need to test and look at

- **payara**
  - > we need to revisit this suite, some project are 'excluded' including this one, but obvious that it is no longer being excluded, and so fails in error
  - Is this a test we should hold off on?

- **scala**
  - > do not think this is related to this PR
  -  Is an issue you guys will handle/track down?

- **tomcat**
  - > requires the APR/native library which is not available
  - This is an issue I am looking into

- **wildfly**
  - Out of Memory Issue and Unset USER environment variable issues
  -  Need to continue to debug this. Running the grinder again with Master to see if there is a change. 

- **wycheproof**
  - >  will have to run locally to see what is expected behaviour (where the test logs get created, maybe something changed since this was added and we have not adapted to it)
  - Is that something you still need to run?

**Comment by james-crowley** [comment]
@ShelleyLambert I just pulled in the changes to master. Should be good to merge. Feel free to merge it!

**Pull request merged**
