### PR TITLE
Update userGuide to include vendor disable feature

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Review by smlambert — APPROVED** [review]
LGTM
Out of curiosity, in the case where we have not mapped vendor to a single word, would this mechanism still work or would one need to use quotes, or put the [mapping in place](https://github.com/AdoptOpenJDK/TKG/blob/master/src/org/openj9/envInfo/JavaInfo.java#L130)?

**Comment by renfeiw** [comment]
> LGTM
> Out of curiosity, in the case where we have not mapped vendor to a single word, would this mechanism still work or would one need to use quotes, or put the [mapping in place](https://github.com/AdoptOpenJDK/TKG/blob/master/src/org/openj9/envInfo/JavaInfo.java#L130)?

In the case, quotes are required. I would do a local test with that to make sure it works.

**Comment by smlambert** [comment]
Its okay, I think if some distributor was using AQA and TKG enough that they wanted to disable tests, we'd add the mapping.  I was just wondering what the behaviour would be.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
