### PR TITLE
Add openjdk8-openj9 as a valid release to run tests against

### PR DESCRIPTION
**Pull request by adamfarley**
This gets validated by jenkinsfile (modified), and passed to go.sh, which uses it for a check that should be compatible with this new value.

Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
JVM_VERSION is used to download binary sdk and openjdk tests.  Should we  update when [openjdk8_openj9_build_x86-64_linux](https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/) and openjdk-api (https://github.com/AdoptOpenJDK/openjdk-api) are ready?

**Comment by adamfarley** [comment]
Catch 22. The build job is ready, and generates viable builds. However, it cannot run the tests because of this blocker. We need to fix this in order to run the build, which then triggers the test.

**Comment by tellison** [comment]
@adoptopenjdk-github-bot add to whitelist

**Comment by karianna** [comment]
@tellison does that unblock what @adamfarley needed?  Just learning here...

**Comment by tellison** [comment]
@karianna No, I was just ensuring that Adam's PRs get any pre-merge testing now and in the future.

I've merged this PR, but wondering why the build job is triggering a test.  Moving the discussion onto Slack.

**Pull request merged**
