### PR TITLE
Use JDK_IMPL_BASE to distinguish implementation

### PR DESCRIPTION
**Pull request by joeyleeeeeee97**
Use base JDK implementation to trigger tests.
Issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2041

### CODE REVIEW

**Comment by smlambert** [comment]
Related: https://github.com/AdoptOpenJDK/TKG/issues/115 - there is a consideration to introduce JDK_VENDOR so as to not convolute JDK_IMPL (which was originally intended to be VM implementation, which would ultimately get used in this template. 

We need not delay this change, but rather revisit the template after a change for TKG 115 is in.

**Comment by karianna** [comment]
> Related: [AdoptOpenJDK/TKG#115](https://github.com/AdoptOpenJDK/TKG/issues/115) - there is a consideration to introduce JDK_VENDOR so as to not convolute JDK_IMPL (which was originally intended to be VM implementation, which would ultimately get used in this template.
> 
> We need not delay this change, but rather revisit the template after a change for TKG 115 is in.

Agreed I'd rather that we use Vendor - but we need to do a pretty major refactor across build, test, API and website for this

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
Tested in internal Test_Job_Auto_Gen_Sandbox (61 and 62) as the script needs Admin approval for running at Adopt Jenkins.

**Comment by llxia** [comment]
@ShelleyLambert I will leave it to you to merge because this script needs to be approved in Adopt Jenkins. Thanks

**Pull request merged**
