### PR TITLE
Add synthetic GC double map test to Mac OSX

### PR DESCRIPTION
**Pull request by bragaigor**
Depends on: https://github.com/eclipse/omr/pull/5580
Depends on: https://github.com/eclipse/openj9/pull/10714

Signed-off-by: Igor Braga <higorb1@gmail.com>

### CODE REVIEW

**Comment by bragaigor** [comment]
Dependent PRs have been merged. This PR is ready

**Review by smlambert — APPROVED** [review]
Thanks @bragaigor - I will run a couple of Grinders before merging, but looks good!

**Comment by smlambert** [comment]
jdk11 j9 xlinux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4703
jdk11 j9 mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4704 - [fails](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4704/tapResults/) (does our nightly build of j9 still not have the upstream code change?)
jdk8 j9 mac: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4705

**Review by smlambert — CHANGES_REQUESTED** [review]
Thanks @bragaigor - I will run a couple of Grinders before merging, but looks good!

**Comment by smlambert** [comment]
@bragaigor - is the expectation that this test is enabled in jdk11 as well?  See above that the Grinder on mac passed in jdk8 but failed for jdk11 with:
SyntheticGCWorkload_DoubleMap_J9_0 Start Time: Fri Nov 13 16:25:25 2020 Epoch Time (ms): 1605284725808
variation: -Xmx2g -Xdump:none -Xgcpolicy:balanced -Xgc:enableArrayletDoubleMapping -verbose:gc
JVM_OPTIONS:  -Xmx2g -Xdump:none -Xgcpolicy:balanced -Xgc:enableArrayletDoubleMapping -verbose:gc 
JVMJ9GC040E Unknown option: enableArrayletDoubleMapping
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to initialize; unable to parse command line
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by bragaigor** [comment]
@ShelleyLambert - I'm not sure why https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4704  failed. Doesn't both JDK8 and JDK11 fetch the same OpenJ9 branch?

And yes, the test is expected to run in JDK11. And I've been using JDK11 in my tests as well, so I'm not sure why it failed

**Comment by smlambert** [comment]
Thanks for confirming @bragaigor 

Checking what is being served up from Adopt API:  
j9 jdk11 nightly 

11:24:52  =JAVA VERSION OUTPUT BEGIN=
11:24:52  openjdk version "11.0.9" 2020-10-20
11:24:52  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11-202011022339)
11:24:52  Eclipse OpenJ9 VM AdoptOpenJDK (build master-40f5a9615, JRE 11 Mac OS X amd64-64-Bit Compressed References 20201102_801 (JIT enabled, AOT enabled)
11:24:52  OpenJ9   - 40f5a9615
11:24:52  OMR      - 4ede03ca6
11:24:52  JCL      - 39a80556b5 based on jdk-11.0.9+11)
11:24:52  =JAVA VERSION OUTPUT END=

j9 jdk8 nightly: 
11:34:15  =JAVA VERSION OUTPUT BEGIN=
11:34:15  openjdk version "1.8.0_275-internal"
11:34:15  OpenJDK Runtime Environment (build 1.8.0_275-internal-202011121744-b01)
11:34:15  Eclipse OpenJ9 VM (build master-06760669e, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20201112_761 (JIT enabled, AOT enabled)
11:34:15  OpenJ9   - 06760669e
11:34:15  OMR      - cb2c463ee
11:34:15  JCL      - 04fa7040 based on jdk8u275-b01)
11:34:15  =JAVA VERSION OUTPUT END=

**Comment by smlambert** [comment]
Respin jdk11 with latest release build (instead of nightly, which seems stale):
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4706

**Comment by bragaigor** [comment]
Ah I see, the OpenJ9 change that enables double mapping was merged 10 days ago here: https://github.com/eclipse/openj9/commit/71c942fe2e9f673f2ab85534a065e0734c88f94b

And the `j9 jdk11 nightly` build fetched `OpenJ9 - 40f5a9615` branch which is 14 days old. While `j9 jdk8 nightly:` fetched a fairly recent branch which is up to date as of yesterday. Which explains why JDK8 test passed and JDK11 failed.

**Comment by smlambert** [comment]
Argh, latest release from API also looks stale:
12:39:12  =JAVA VERSION OUTPUT BEGIN=
12:39:12  openjdk version "11.0.9" 2020-10-20
12:39:12  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
12:39:12  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20201023_788 (JIT enabled, AOT enabled)
12:39:12  OpenJ9   - 0394ef754
12:39:12  OMR      - 582366ae5
12:39:12  JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)
12:39:12  =JAVA VERSION OUTPUT END=

I had assumed the builds [published today](https://github.com/AdoptOpenJDK/TSC/issues/185#issuecomment-726872869) would have been served up already.

Respin from today's build:

**Review by smlambert — APPROVED** [review]

**Pull request merged**
