### PR TITLE
Using nightly JDK Image as default target

### LINKED ISSUE #1549: external functional-test get compilation error with openj9
**Describe the bug**
External functional-test get compilation error with openj9 jdk8

**To Reproduce**
Rerun link https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=external/functional-test&PLATFORM=x86-64_linux&TARGET=special&SDK_RESOURCE=nightly

```
16:55:33  compile:
16:55:33       [echo] Ant version is Apache Ant(TM) version 1.10.5 compiled on March 28 2019
16:55:33       [echo] ============COMPILER SETTINGS============
16:55:33       [echo] ===fork:                         yes
16:55:33       [echo] ===executable:                   /opt/java/openjdk/bin/javac
16:55:33       [echo] ===debug:                        on
16:55:33       [echo] ===destdir:                      /openj9/test/TKG/../../jvmtest/functional/CacheManagement
16:55:33      [javac] Compiling 4 source files to /openj9/test/functional/CacheManagement/testcodebuild
16:55:35      [javac] Compiling 4 source files to /openj9/test/functional/CacheManagement/bin
16:55:35      [javac] Compiling 98 source files to /openj9/test/functional/CacheManagement/bin
16:55:42      [javac] /openj9/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java:232: error: cannot find symbol
16:55:42      [javac] 							if (cacheInfo.getCacheLayer() != 0) {
16:55:42      [javac] 							             ^
16:55:42      [javac]   symbol:   method getCacheLayer()
16:55:42      [javac]   location: variable cacheInfo of type SharedClassCacheInfo
16:55:42      [javac] /openj9/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java:234: error: cannot find symbol
16:55:42      [javac] 								if ((cacheInfo.getCacheName().equals("cache3_multilayercache")) && (1 == 
```

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by sophia-guo**
close #1549 

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Updated Grinder with params.DOCKERIMAGE_TAG ( setting  nightly as default)

**Comment by sophia-guo** [comment]
Grinder take functional as test:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1075/console

```
23:46:26  Using docker image default Java
23:46:26  openjdk version "1.8.0_242"
23:46:26  OpenJDK Runtime Environment (build 1.8.0_242-202001020429-b05)
23:46:26  Eclipse OpenJ9 VM (build master-a873af9c2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200102_486 (JIT enabled, AOT enabled)
23:46:26  OpenJ9   - a873af9c2
23:46:26  OMR      - ce7fdb230
23:46:26  JCL      - fbdf154d48b based on jdk8u242-b05)
23:46:26  JAVA_HOME is : /opt/java/openjdk
```
Failure is functional dependency issue, will open another issue.

**Comment by smlambert** [comment]
FYI @james-crowley - for any failures you are seeing in your PR Grinder runs, will be worth trying with nightly tags.  I will like to merge this ahead of yours, so you can pick up these defaults.

**Comment by sophia-guo** [comment]
New grinder:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1083/tapResults/

**Pull request merged**
