### PR TITLE
Accommodate other possible Docker base images

### PR DESCRIPTION
**Pull request by sophia-guo**
1. Set Docker base image tag in parent build.xml
2. Import parent build.xml. Otherwise when setting BUILD_LIST to
specific subproject, targets in parent build.xml do not run actually.

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Related with #1134

**Comment by sophia-guo** [comment]
Grinder to test with alpine tag
`16:11:27       [exec] alpine: Pulling from adoptopenjdk/openjdk11`
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Sandbox/404/console
Failures show Docker base image with alpine have the issue about running `apt-get update && apt-get -y install ...` .

**Comment by sophia-guo** [comment]
This will also fix some leftover base images on test machines.
Screen Shot 2019-05-16 at 12 10 32 PM

**Comment by smlambert** [comment]
There is a conflict that needs resolved for this one.

**Comment by sophia-guo** [comment]
Thanks @smlambert conflict resolved.

**Pull request merged**
