### PR TITLE
Remove export of JAVA_HOME from system test playlists build scripts

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/AdoptOpenJDK/openjdk-tests/issues/1001
Signed-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
Testing (In progress): `sanity.system` target with JDK11 on hotspot: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1389/console

Testing (In progress) `excended.system` target with JDK8 on OpenJ9: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1390/console

**Comment by sophia-guo** [comment]
The grinder shows 'TOTAL: 26   EXECUTED: 25   PASSED: 0   FAILED: 25   SKIPPED: 1'.  And another grinder is still running. This should still be WIP?

**Comment by Mesbah-Alam** [comment]
@sophia-guo : yes, the changes don't work yet on Java 8 as you pointed out. I've marked this issue WIP.

**Comment by Mesbah-Alam** [comment]
The reason for the failure in Java 8 build is somehow STF is constructing wrong path for the Java executable: 

```/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/bin/java```
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1390/tapResults/

However, If set 

```
JDK_HOME := $(JAVA_BIN_TMP)$(D)..$(D)..
```

i.e. : https://github.com/eclipse/openj9/compare/master...Mesbah-Alam:updateJavaHomeExport?expand=1

The test starts working "magically" : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1391/

I need to figure out why this happens. 

The only change I made is remove JAVA_HOME export from the stf.pl test command line in the playlist, since JAVA_HOME is now being exported in TKG.. But obviously something is not working properly somewhere..

**Comment by Mesbah-Alam** [comment]
Note, if we export JAVA_HOME as part of the stf command line in the playlist, the test works fine: 

Java 8 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1405/consoleFull
Java 11: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1407/console

We should find out if the JAVA_HOME export is actually taking effect at the playlist level.

**Comment by Mesbah-Alam** [comment]
Ran another test with echo in the playlist and it shows that JAVA_HOME is showing correct value from the playlsit level. 

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1408/console

```
echo /JAVA_HOME from playlist = /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/../../  && \

```

Note that, in the "generation" stage, we have correct path being constructed for the java executable: 

```
11:00:15  STF 15:00:14.694 - ==================   G E N E R A T I O N   ==================
11:00:15  STF 15:00:14.697 - Checking JVM: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/../..
11:00:15  STF 15:00:14.697 - Starting process to generate scripts: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/../../bin/java 

```

However, in the "execute" stage, we are seeing Java executable path being constructed wrongly: 

```
11:00:17  STF 15:00:16.884 - ====================   E X E C U T E -   ====================
11:00:17  STF 15:00:16.884 - Running execute: perl /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15542172133308/ClassLoadingTest_0/20190402-150014-ClassloadingLoadTest/execute.pl
11:00:17  STF 15:00:17.035 - 
11:00:17  STF 15:00:17.035 - Java version
11:00:17  STF 15:00:17.035 - Running: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/bin/java -version
11:00:17  STF 15:00:17.037 - 
11:00:17  STF 15:00:17.038 - +------ Step 1 - Run classloading tests
11:00:17  STF 15:00:17.038 - | Run foreground process
11:00:17  STF 15:00:17.038 - |   Program:     /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/bin/java
11:00:17  STF 15:00:17.038 - |   Mnemonic:    CLT
11:00:17  STF 15:00:17.038 - |   Echo:        ECHO_ON
11:00:17  STF 15:00:17.038 - |   Expectation: CLEAN_RUN within 2h
11:00:17  STF 15:00:17.038 - |
11:00:17  STF 15:00:17.039 - Running command: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/bin/java
```

The problem is in this path /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-imag**e/jre/bin/bin/java**

**Comment by Mesbah-Alam** [comment]
The culprit is : https://github.com/AdoptOpenJDK/stf/blob/7327579a6c29ca76211c1a3750db81e8476b14cf/stf.core/src/stf.core/net/adoptopenjdk/stf/environment/DirectoryRef.java#L75 

As [this](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/84/console) debug output shows, the trailing "../.." is being chopped off by STF while creating the DirectoryRef with the PATH of JAVA_HOME. 

I'll fix this.

**Comment by Mesbah-Alam** [comment]
Re-ran a `sanity.system` build on openj9 jdk8 with this PR after https://github.com/AdoptOpenJDK/stf/issues/58 was delivered. 

All tests are passing now: 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1410/

@sophia-guo - please review.

**Comment by Mesbah-Alam** [comment]
Test with jdk11 are working fine as well: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1411/

**Pull request merged**
