### PR TITLE
Remove duplicate parameters in personal build jenkins

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Another choice is using yml to setup those variables. Will try that.

**Comment by sophia-guo** [comment]
May use yaml for jenkinsbase and personaljenkins later in separate PR.

**Comment by smlambert** [comment]
Thanks, also, separate task to update the wiki page too.
https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Personal-Test-Build-on-Jenkins

**Comment by sophia-guo** [comment]
Yes, will update the wiki

**Pull request merged**
