### PR TITLE
Rename thirdparty_containers to external to match top-level test target

### PR DESCRIPTION
**Pull request by sophia-guo**
Related with #980 

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Note:
   1.  testJobTemplate is updated, so we need to approve the script in order for Test_Job_Auto_Gen to run
   2. Grinder BUILD_LIST description needs to be updated on three sites
   3. External parent job configuration need to update

**Comment by sophia-guo** [comment]
Grinder: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/409/consoleFull

**Comment by sophia-guo** [comment]
Grinder : https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/409/consoleFull

**Comment by sophia-guo** [comment]
@llxia I will probably leave it to you to merge as the script need to be approved by jenkins. Once it is merged I will update the external parent jobs.

**Comment by llxia** [comment]
Done. The script is approved in both Jenkins.

**Comment by sophia-guo** [comment]
The parents jobs updated. Grinder jobs in Adopt and IBM are updated. May need help @ShelleyLambert to updated grinder jobs in Openj9. ( I have no permission).

**Comment by smlambert** [comment]
Thanks @sophia-guo - I have updated the openj9 grinder jobs.

**Pull request merged**
