### PR TITLE
Fix unmount JDK JAVA_HOME directory

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Fix recent external test failure
 ```
21:55:38 Error: JAVA_HOME is not defined correctly.
21:55:38   We cannot execute /java/bin/java
21:55:38 Error: JAVA_HOME is not defined correctly.
21:55:38   We cannot execute /java/bin/java
```
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk11_j9_externaltest_x86-64_linux/101/consoleFull

**Comment by sophia-guo** [comment]
Grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/862/consoleFull
JAVA_HOME issue fixed. Failed for later steps.

**Comment by smlambert** [comment]
Can you additionally run a grinder passing in via EXTRA_DOCKER_ARGS, as per https://github.com/AdoptOpenJDK/openjdk-tests/pull/777 (you will have to add that to the Grinder config in Jenkins, as its not yet been added)

**Comment by sophia-guo** [comment]
functional-test has its own setup of JAVA_HOME. Not sure why and didn't touch it yet. @chandrams

**Comment by sophia-guo** [comment]
@ShelleyLambert sure, will try it first in grinder_sandbox.

**Pull request merged**
