### PR TITLE
Add third party test example

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
This PR has been tested using the following personal build: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/64/console

**Comment by Mesbah-Alam** [comment]
@ShelleyLambert Hi Shelley, please review the PR when possible. I have added some comments indicating some of the typical spots that need to be changed / replaced when new third party container tests will be added based on this example.

**Comment by smlambert** [comment]
tpc-example is actually a public repo I created on github (completely standalone from AdoptOpenJDK).  Eventually we can replace it with something else, but it is just meant to show you can pull from any repo, and in the case of the list of 3rd party apps we want to add, that line will be replaced with their git repos.

**Comment by smlambert** [comment]
@Mesbah-Alam You seem to have a scala/playlist.xml.bkup file in your PR

**Comment by Mesbah-Alam** [comment]
@smlambert yes, I've removed playlist.xml.bkup :)

**Pull request merged**
