### PR TITLE
Fix several test cases in MBCS_Tests

### PR DESCRIPTION
**Pull request by KKES335**
In several test cases,  compile fails with JDK8 because of missing Runtime.version() in Java8.
We fix the above issue by using the Reflection.

### CODE REVIEW

**Comment by KKES335** [comment]
Fixes #1235
Signed-off-by: Kentaro Kuramochi kkes335@jp.ibm.com

**Comment by KKES335** [comment]
Windows  Java8 - openj9
98 tests, 34 ok, 0 not ok, 64 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1836/console

**Comment by KKES335** [comment]
AIX Java8 - openj9
98 tests, 39 ok, 0 not ok, 59 skipped, 0 ToDo, 0 Bail Out!
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1835/consoleFull

**Comment by smlambert** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1922
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1923/tapResults/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1924/

Compiles seem to work across the platforms now, thanks @KKES335 

We still have some test failures not captured in the issue this addresses #1235

**Pull request merged**
