### PR TITLE
Add 1 hour timeouts to all copyArtifacts steps

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Avoid long hanging builds when copyArtifacts hangs

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Looking for feedback @llxia 
I have been finding jobs hung for hours on the copyArtifacts step. This ties up machine time. I have wrapped all the copyArtifact steps in 1 hour timeouts. We can keep some or all or we can adjust the times to our liking. What are your thoughts? If you wish I can provide some links to internal builds I have come across.

**Comment by llxia** [comment]
Screenshot:
image

**Review by llxia — APPROVED** [review]
LGTM

**Review by smlambert — APPROVED** [review]
LGTM

**Comment by smlambert** [comment]
Script approved at Adopt server.

**Pull request merged**
